import { AlertTriangle, CheckCircle2, ClipboardList, Lightbulb, ShieldAlert } from "lucide-react"

function list(values, fallback = []) {
  if (Array.isArray(values)) return values.filter(Boolean)
  if (values) return [values]
  return fallback
}

function toneFor(value = "") {
  const text = String(value).toLowerCase()
  if (/critical|high|suspicious|malicious|danger|blocked|failed/.test(text)) return "danger"
  if (/medium|review|warning|unknown|partial|limited/.test(text)) return "warning"
  if (/low|clean|ok|success|ready|complete|benign/.test(text)) return "success"
  return "info"
}

function ToneIcon({ tone }) {
  if (tone === "danger") return <ShieldAlert className="h-5 w-5" />
  if (tone === "warning") return <AlertTriangle className="h-5 w-5" />
  if (tone === "success") return <CheckCircle2 className="h-5 w-5" />
  return <ClipboardList className="h-5 w-5" />
}

function ReviewSection({ title, tone, items, fallback, action = false }) {
  const values = items.length ? items : [fallback]
  return (
    <section className={`ba-output-review-section is-${tone}`}>
      <div className="ba-output-review-section-title">
        <span>{title}</span>
        <b>{values.length}</b>
      </div>
      <ul>
        {values.map((item) => (
          <li key={String(item)}>
            {action ? <Lightbulb className="h-3.5 w-3.5" /> : null}
            <span>{String(item)}</span>
          </li>
        ))}
      </ul>
    </section>
  )
}

export default function AnalystOutputCard({
  title = "Analyst output review",
  subtitle = "Case-ready interpretation",
  verdict = "Needs analyst review",
  confidence = "local heuristic",
  summary = "Review generated output and verify source context before acting.",
  evidence = [],
  limitations = [],
  nextActions = [],
  metrics = [],
}) {
  const tone = toneFor(`${verdict} ${confidence}`)
  const evidenceItems = list(evidence).slice(0, 5)
  const limitationItems = list(limitations, ["Local/static output only. Validate with authoritative logs, user reports, and approved external sources when needed."]).slice(0, 4)
  const actionItems = list(nextActions, ["Preserve raw evidence.", "Add key findings to the case timeline/report.", "Pivot only on scoped and authorized artifacts."]).slice(0, 5)
  const metricItems = list(metrics).filter((item) => Array.isArray(item) && item.length >= 2).slice(0, 6)

  return (
    <section className={`ba-output-review ba-output-review-${tone}`}>
      <div className="ba-output-review-head">
        <div className="ba-output-review-icon"><ToneIcon tone={tone} /></div>
        <div>
          <p className="ba-eyebrow">{subtitle}</p>
          <h2>{title}</h2>
          <p>{summary}</p>
        </div>
        <div className="ba-output-review-badges">
          <span>{verdict}</span>
          <span>{confidence}</span>
        </div>
      </div>

      {metricItems.length ? (
        <dl className="ba-output-review-metrics">
          {metricItems.map(([label, value]) => (
            <div key={label}>
              <dt>{label}</dt>
              <dd>{value || "—"}</dd>
            </div>
          ))}
        </dl>
      ) : null}

      <div className="ba-output-review-grid">
        <ReviewSection title="Evidence used" tone="evidence" items={evidenceItems} fallback="No high-confidence evidence was generated by this module." />
        <ReviewSection title="Limitations" tone="limitations" items={limitationItems} fallback="Local/static output only. Validate with authoritative evidence before acting." />
        <ReviewSection title="Next actions" tone="actions" items={actionItems} fallback="Preserve raw evidence and add validated findings to the case timeline." action />
      </div>
    </section>
  )
}
