from datetime import datetime, timezone


def build_markdown_report(title: str, summary: str, sections: list[dict], recommendations: list[str], analyst: str = "") -> dict:
    timestamp = datetime.now(timezone.utc).isoformat()

    lines = [
        f"# {title}",
        "",
        "## Metadata",
        "- Generated By: BeyondArch",
        f"- Analyst: {analyst or 'N/A'}",
        f"- Timestamp UTC: {timestamp}",
        "",
        "## Summary",
        summary or "N/A",
        "",
    ]

    for section in sections:
        section_title = section.get("title", "Untitled Section")
        content = section.get("content", "")

        lines.append(f"## {section_title}")

        if isinstance(content, list):
            for item in content:
                lines.append(f"- {item}")
        else:
            lines.append(str(content) if content else "N/A")

        lines.append("")

    lines.append("## Recommendations")

    if recommendations:
        for recommendation in recommendations:
            lines.append(f"- {recommendation}")
    else:
        lines.append("- N/A")

    return {
        "title": title,
        "analyst": analyst,
        "timestamp_utc": timestamp,
        "report_markdown": "\n".join(lines),
    }
