"""Local SOC reference data for common Windows Security and Sysmon events.

This is intentionally curated for defensive triage. It is not an external lookup and it
should grow over time as BeyondLabs adds more analyst reference content.
"""

WINDOWS_EVENTS = {
    "4624": {
        "title": "Successful Logon",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Records successful account access. It is baseline telemetry, but becomes important when the source, logon type, account, or timing is unusual.",
        "fields": ["Account Name", "Account Domain", "Logon Type", "Source Network Address", "Workstation Name", "Logon ID", "Authentication Package"],
        "triage": [
            "Check logon type: 2 interactive, 3 network, 7 unlock, 10 remote interactive, 11 cached interactive.",
            "Correlate with failed 4625 events before the success from the same source or against the same account.",
            "Review whether the account/source host is expected for the asset and time window.",
            "For privileged accounts, correlate with 4672 and subsequent process creation events."
        ],
        "severity_hint": "info",
        "false_positives": ["Normal user login", "Service account authentication", "Administrative maintenance"],
        "related_events": ["4625", "4672", "4648", "4688"],
        "sample_spl": "EventCode=4624 | stats count by Account_Name,Logon_Type,Source_Network_Address",
    },
    "4625": {
        "title": "Failed Logon",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Repeated failed logons can indicate brute force, password spraying, exposed remote access, or misconfigured services.",
        "fields": ["Account Name", "Failure Reason", "Status", "Sub Status", "Source Network Address", "Logon Type", "Workstation Name"],
        "triage": [
            "Group by Source Network Address and Account Name to identify spraying versus single-account brute force.",
            "Check status/substatus values to distinguish invalid user, bad password, locked account, and policy failures.",
            "Look for a successful 4624 after a burst of 4625 events.",
            "Correlate with VPN, RDP, firewall, or cloud identity logs when available."
        ],
        "severity_hint": "medium",
        "false_positives": ["Password typo", "Expired cached credentials", "Service account password rotation issue"],
        "related_events": ["4624", "4740", "4771", "4776"],
        "sample_spl": "EventCode=4625 | stats count by Source_Network_Address,Account_Name | sort -count",
    },
    "4648": {
        "title": "Logon Using Explicit Credentials",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Shows a process using explicit credentials. Useful for detecting lateral movement, runas usage, alternate credentials, and credential misuse.",
        "fields": ["Subject Account Name", "Account Whose Credentials Were Used", "Target Server Name", "Process Name", "Network Address"],
        "triage": ["Validate the process that used credentials.", "Check whether the target server is expected.", "Correlate with 4624 on the destination host."],
        "severity_hint": "medium",
        "false_positives": ["Administrative runas", "Scheduled task or management tool"],
        "related_events": ["4624", "4688", "4672"],
        "sample_spl": "EventCode=4648 | table _time,host,Subject_Account_Name,Target_Server_Name,Process_Name",
    },
    "4672": {
        "title": "Special Privileges Assigned to New Logon",
        "event_source": "Windows Security",
        "category": "Privilege Use",
        "why_it_matters": "Indicates an account logged on with administrator-level privileges. Important when paired with unusual source, time, or follow-on activity.",
        "fields": ["Account Name", "Account Domain", "Privileges", "Logon ID"],
        "triage": ["Verify whether the account is expected to be privileged.", "Correlate with 4624 by Logon ID.", "Review subsequent 4688 process creation and administrative changes."],
        "severity_hint": "medium",
        "false_positives": ["Normal administrator login", "Domain admin maintenance"],
        "related_events": ["4624", "4688", "4728", "4732"],
        "sample_spl": "EventCode=4672 | stats count by Account_Name,host",
    },
    "4688": {
        "title": "Process Creation",
        "event_source": "Windows Security",
        "category": "Process Monitoring",
        "why_it_matters": "Core endpoint telemetry for command execution, script activity, living-off-the-land binaries, and parent/child process chains.",
        "fields": ["New Process Name", "Creator Process Name", "Process Command Line", "Account Name", "Token Elevation Type"],
        "triage": ["Review command line arguments and parent process.", "Hunt for PowerShell, cmd, rundll32, regsvr32, certutil, mshta, wscript, cscript, bitsadmin, schtasks.", "Correlate with network, file, registry, and authentication events."],
        "severity_hint": "medium",
        "false_positives": ["Administration scripts", "Software deployment", "Login scripts"],
        "related_events": ["4624", "4672", "Sysmon 1", "Sysmon 3", "Sysmon 11"],
        "sample_spl": "EventCode=4688 (New_Process_Name=*powershell.exe OR Process_Command_Line=*EncodedCommand*) | table _time,host,Account_Name,New_Process_Name,Creator_Process_Name,Process_Command_Line",
    },
    "4697": {
        "title": "Service Installed in the System",
        "event_source": "Windows Security",
        "category": "Persistence",
        "why_it_matters": "New service creation can indicate persistence, remote administration, or malware installation.",
        "fields": ["Service Name", "Service File Name", "Service Type", "Service Start Type", "Account Name"],
        "triage": ["Review service binary path and signer.", "Check if service creation aligns with change window.", "Correlate with 7045 and process creation."],
        "severity_hint": "high",
        "false_positives": ["Software installation", "Agent deployment"],
        "related_events": ["7045", "4688", "Sysmon 6"],
        "sample_spl": "EventCode=4697 | table _time,host,Service_Name,Service_File_Name,Account_Name",
    },
    "4698": {
        "title": "Scheduled Task Created",
        "event_source": "Windows Security",
        "category": "Persistence",
        "why_it_matters": "Scheduled tasks are common for persistence and administrative automation. Unexpected task creation deserves review.",
        "fields": ["Task Name", "Task Content", "Subject Account Name"],
        "triage": ["Inspect the task action and trigger.", "Check file path, command arguments, and account used.", "Look for encoded PowerShell or suspicious script locations."],
        "severity_hint": "high",
        "false_positives": ["Legitimate software updater", "Admin automation"],
        "related_events": ["4702", "4688", "Sysmon 1", "Sysmon 11"],
        "sample_spl": "EventCode=4698 | table _time,host,Task_Name,Subject_Account_Name,Task_Content",
    },
    "4702": {
        "title": "Scheduled Task Updated",
        "event_source": "Windows Security",
        "category": "Persistence",
        "why_it_matters": "Task modification can indicate persistence tuning or hijacking of existing scheduled tasks.",
        "fields": ["Task Name", "Task Content", "Subject Account Name"],
        "triage": ["Compare old/new task content if available.", "Review the executable path and trigger.", "Correlate with recent admin logons."],
        "severity_hint": "medium",
        "false_positives": ["Patch tooling", "Software updater"],
        "related_events": ["4698", "4688"],
        "sample_spl": "EventCode=4702 | table _time,host,Task_Name,Subject_Account_Name",
    },
    "4720": {
        "title": "User Account Created",
        "event_source": "Windows Security",
        "category": "Account Management",
        "why_it_matters": "Unexpected account creation can indicate persistence or unauthorized administration.",
        "fields": ["New Account Name", "Creator Account Name", "Account Domain", "User Principal Name"],
        "triage": ["Verify whether the account was created through an approved process.", "Check whether it was added to privileged groups.", "Review source host and creator account activity."],
        "severity_hint": "high",
        "false_positives": ["Helpdesk onboarding", "Admin provisioning"],
        "related_events": ["4722", "4728", "4732", "4672"],
        "sample_spl": "EventCode=4720 | table _time,host,Creator_Account_Name,New_Account_Name",
    },
    "4722": {
        "title": "User Account Enabled",
        "event_source": "Windows Security",
        "category": "Account Management",
        "why_it_matters": "Enabling a disabled account can be normal administration or attacker reactivation of dormant access.",
        "fields": ["Target Account", "Subject Account Name"],
        "triage": ["Check age and purpose of the account.", "Correlate with group additions and successful logons."],
        "severity_hint": "medium",
        "false_positives": ["Account reactivation request"],
        "related_events": ["4720", "4728", "4624"],
        "sample_spl": "EventCode=4722 | table _time,host,Subject_Account_Name,Target_Account_Name",
    },
    "4728": {
        "title": "Member Added to Global Security Group",
        "event_source": "Windows Security",
        "category": "Privilege Change",
        "why_it_matters": "Group membership changes can grant privilege. High-value when the group is privileged or the actor is unusual.",
        "fields": ["Member Name", "Group Name", "Subject Account Name", "Target Domain"],
        "triage": ["Determine if the target group is privileged.", "Validate change ticket or admin action.", "Correlate with account creation and logons."],
        "severity_hint": "high",
        "false_positives": ["Approved role change", "Helpdesk group update"],
        "related_events": ["4732", "4756", "4720", "4672"],
        "sample_spl": "EventCode IN (4728,4732,4756) | table _time,host,Subject_Account_Name,Member_Name,Group_Name",
    },
    "4732": {
        "title": "Member Added to Local Security Group",
        "event_source": "Windows Security",
        "category": "Privilege Change",
        "why_it_matters": "Local Administrators or Remote Desktop Users additions can create immediate host-level privilege or remote access.",
        "fields": ["Member Name", "Group Name", "Subject Account Name"],
        "triage": ["Check if group is Administrators, Remote Desktop Users, or Backup Operators.", "Review actor account and originating host."],
        "severity_hint": "high",
        "false_positives": ["Admin maintenance", "Endpoint management tool"],
        "related_events": ["4728", "4624", "4672"],
        "sample_spl": "EventCode=4732 | search Group_Name=*Administrators* OR Group_Name=*Remote*",
    },
    "4740": {
        "title": "User Account Locked Out",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Account lockouts can reveal brute force, password spraying, stale credentials, or service misconfiguration.",
        "fields": ["Target Account Name", "Caller Computer Name"],
        "triage": ["Identify caller computer and repeated target accounts.", "Correlate with 4625 and 4771/4776 failures."],
        "severity_hint": "medium",
        "false_positives": ["Stale password in mapped drive/service", "User typo"],
        "related_events": ["4625", "4771", "4776"],
        "sample_spl": "EventCode=4740 | stats count by Target_Account_Name,Caller_Computer_Name",
    },
    "4771": {
        "title": "Kerberos Pre-authentication Failed",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Kerberos failure telemetry useful for password spray, expired passwords, and domain auth troubleshooting.",
        "fields": ["Account Name", "Client Address", "Failure Code", "Pre-Authentication Type"],
        "triage": ["Group by client address and account.", "Decode failure code context.", "Correlate with lockouts and successful logons."],
        "severity_hint": "medium",
        "false_positives": ["Expired password", "Clock skew", "User typo"],
        "related_events": ["4625", "4740", "4768"],
        "sample_spl": "EventCode=4771 | stats count by Client_Address,Account_Name,Failure_Code",
    },
    "4768": {
        "title": "Kerberos Authentication Ticket Requested",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Baseline Kerberos authentication. Useful when correlating Kerberos failures, ticket anomalies, and account activity.",
        "fields": ["Account Name", "Client Address", "Ticket Encryption Type", "Result Code"],
        "triage": ["Review unusual encryption types or result codes.", "Correlate with 4771 failures and 4769 service ticket requests."],
        "severity_hint": "info",
        "false_positives": ["Normal domain authentication"],
        "related_events": ["4769", "4771"],
        "sample_spl": "EventCode=4768 | stats count by Account_Name,Client_Address,Ticket_Encryption_Type",
    },
    "4769": {
        "title": "Kerberos Service Ticket Requested",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Useful for service access and Kerberoasting investigations when unusual service names or encryption types appear.",
        "fields": ["Account Name", "Service Name", "Client Address", "Ticket Encryption Type"],
        "triage": ["Look for many service tickets by one user.", "Review RC4 encryption where unexpected.", "Correlate with service account exposure."],
        "severity_hint": "medium",
        "false_positives": ["Normal application access", "Service discovery"],
        "related_events": ["4768", "4771", "4624"],
        "sample_spl": "EventCode=4769 | stats count by Account_Name,Service_Name,Ticket_Encryption_Type | sort -count",
    },
    "4776": {
        "title": "NTLM Authentication Attempt",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Shows NTLM credential validation. Useful for legacy auth, brute force, and lateral movement context.",
        "fields": ["Account Name", "Workstation", "Status"],
        "triage": ["Group failures by workstation and user.", "Investigate NTLM usage where Kerberos is expected."],
        "severity_hint": "medium",
        "false_positives": ["Legacy application authentication"],
        "related_events": ["4625", "4624", "4740"],
        "sample_spl": "EventCode=4776 | stats count by Workstation,Account_Name,Status",
    },
    "5140": {
        "title": "Network Share Object Accessed",
        "event_source": "Windows Security",
        "category": "Object Access",
        "why_it_matters": "Useful for tracking SMB share access, lateral movement, and suspicious access to admin shares.",
        "fields": ["Share Name", "Account Name", "Source Address", "Access Mask"],
        "triage": ["Look for access to C$, ADMIN$, IPC$, or sensitive shares.", "Correlate with 4624 logon type 3 and process activity."],
        "severity_hint": "medium",
        "false_positives": ["Normal file share access", "Backup operations"],
        "related_events": ["4624", "5145", "4688"],
        "sample_spl": "EventCode=5140 | stats count by Share_Name,Account_Name,Source_Address",
    },
    "5145": {
        "title": "Detailed File Share Access",
        "event_source": "Windows Security",
        "category": "Object Access",
        "why_it_matters": "Detailed SMB file access can reveal lateral movement, staging, or suspicious file reads/writes.",
        "fields": ["Share Name", "Relative Target Name", "Accesses", "Source Address"],
        "triage": ["Review suspicious paths and write access.", "Correlate with source IP and account activity."],
        "severity_hint": "medium",
        "false_positives": ["Normal user file access"],
        "related_events": ["5140", "4624"],
        "sample_spl": "EventCode=5145 | table _time,host,Account_Name,Share_Name,Relative_Target_Name,Accesses,Source_Address",
    },
    "1102": {
        "title": "Audit Log Cleared",
        "event_source": "Windows Security",
        "category": "Defense Evasion",
        "why_it_matters": "Clearing audit logs is a high-signal defense-evasion event unless tied to expected maintenance.",
        "fields": ["Subject Account Name", "Computer", "Logon ID"],
        "triage": ["Treat as suspicious until explained.", "Identify the account and source session.", "Look backward for process, logon, and privilege events before the clear."],
        "severity_hint": "high",
        "false_positives": ["Maintenance or log reset procedure"],
        "related_events": ["4624", "4672", "4688"],
        "sample_spl": "EventCode=1102 | table _time,host,Subject_Account_Name",
    },
    "7045": {
        "title": "Service Installed",
        "event_source": "System / Service Control Manager",
        "category": "Persistence",
        "why_it_matters": "Service creation is frequently used for software installation, remote administration, and persistence. Unexpected services require review.",
        "fields": ["Service Name", "Service File Name", "Service Type", "Start Type", "Account Name"],
        "triage": ["Inspect service file path and command line.", "Check signer/hash and whether path is in Temp, AppData, ProgramData, or user profile.", "Correlate with 4624/4672 and process creation before installation."],
        "severity_hint": "high",
        "false_positives": ["Legitimate software install", "EDR/management agent deployment"],
        "related_events": ["4697", "4688", "Sysmon 1", "Sysmon 6"],
        "sample_spl": "EventCode=7045 | table _time,host,Service_Name,Service_File_Name,Account_Name",
    },
}

SYSMON_EVENTS = {
    "sysmon:1": {
        "event_id": "1",
        "title": "Process Create",
        "event_source": "Sysmon",
        "category": "Process Monitoring",
        "why_it_matters": "High-value process telemetry including image, command line, parent, hashes, user, and integrity context.",
        "fields": ["Image", "CommandLine", "ParentImage", "ParentCommandLine", "User", "Hashes", "ProcessGuid"],
        "triage": ["Review parent/child relationship.", "Hunt for LOLBins, encoded commands, script interpreters, and suspicious paths.", "Correlate ProcessGuid with network, file, registry, and DNS Sysmon events."],
        "severity_hint": "medium",
        "false_positives": ["Admin scripts", "Software deployment", "Developer tooling"],
        "related_events": ["Sysmon 3", "Sysmon 11", "Sysmon 22", "4688"],
        "sample_spl": "sourcetype=sysmon EventCode=1 | table _time,host,User,Image,CommandLine,ParentImage",
    },
    "sysmon:3": {
        "event_id": "3",
        "title": "Network Connection",
        "event_source": "Sysmon",
        "category": "Network",
        "why_it_matters": "Connects process activity to remote IP/domain and port. Useful for C2, downloaders, and suspicious outbound connections.",
        "fields": ["Image", "DestinationIp", "DestinationHostname", "DestinationPort", "Protocol", "User"],
        "triage": ["Check whether the process normally makes outbound network connections.", "Review destination reputation/context using local recon where appropriate.", "Correlate with process creation and DNS query events."],
        "severity_hint": "medium",
        "false_positives": ["Browser/network apps", "Update services"],
        "related_events": ["Sysmon 1", "Sysmon 22"],
        "sample_spl": "sourcetype=sysmon EventCode=3 | stats count by Image,DestinationIp,DestinationPort",
    },
    "sysmon:7": {
        "event_id": "7",
        "title": "Image Loaded",
        "event_source": "Sysmon",
        "category": "Module Load",
        "why_it_matters": "Can support DLL hijacking, suspicious module load, and unsigned DLL investigations when tuned carefully.",
        "fields": ["Image", "ImageLoaded", "Signed", "Signature", "Hashes"],
        "triage": ["Focus on unusual directories, unsigned modules, and sensitive process loads.", "High-volume event; tune before production."],
        "severity_hint": "low",
        "false_positives": ["Normal DLL loading", "Noisy telemetry"],
        "related_events": ["Sysmon 1"],
        "sample_spl": "sourcetype=sysmon EventCode=7 Signed=false | table _time,host,Image,ImageLoaded,Signature",
    },
    "sysmon:10": {
        "event_id": "10",
        "title": "Process Access",
        "event_source": "Sysmon",
        "category": "Credential Access",
        "why_it_matters": "Can reveal process injection, credential dumping attempts, or suspicious access to sensitive processes such as lsass.exe.",
        "fields": ["SourceImage", "TargetImage", "GrantedAccess", "CallTrace", "SourceProcessGuid", "TargetProcessGuid"],
        "triage": ["Review access to lsass.exe and browser/credential stores.", "Correlate with process creation and hashes.", "Validate EDR/AV or backup false positives."],
        "severity_hint": "high",
        "false_positives": ["EDR/AV inspection", "Backup/security tools"],
        "related_events": ["Sysmon 1", "4688"],
        "sample_spl": "sourcetype=sysmon EventCode=10 TargetImage=*lsass.exe | table _time,host,SourceImage,GrantedAccess,CallTrace",
    },
    "sysmon:11": {
        "event_id": "11",
        "title": "File Create",
        "event_source": "Sysmon",
        "category": "File Activity",
        "why_it_matters": "Tracks created files and can show payload drops, staged scripts, persistence artifacts, and suspicious write locations.",
        "fields": ["Image", "TargetFilename", "CreationUtcTime", "User"],
        "triage": ["Review writes to startup, temp, user profile, public, or web-root paths.", "Correlate file creation with process and network activity."],
        "severity_hint": "medium",
        "false_positives": ["Software install/update", "Browser downloads"],
        "related_events": ["Sysmon 1", "Sysmon 3", "Sysmon 15"],
        "sample_spl": "sourcetype=sysmon EventCode=11 TargetFilename IN (*\\AppData\\*,*\\Temp\\*,*\\Startup\\*)",
    },
    "sysmon:12": {
        "event_id": "12",
        "title": "Registry Object Created/Deleted",
        "event_source": "Sysmon",
        "category": "Registry",
        "why_it_matters": "Registry changes are useful for persistence, configuration tampering, and system modification investigations.",
        "fields": ["Image", "TargetObject", "EventType", "User"],
        "triage": ["Focus on Run keys, services, WMI, IFEO, and security product keys.", "Correlate with process creation."],
        "severity_hint": "medium",
        "false_positives": ["Installer activity", "Policy updates"],
        "related_events": ["Sysmon 13", "Sysmon 14", "4688"],
        "sample_spl": "sourcetype=sysmon EventCode=12 TargetObject=*\\CurrentVersion\\Run*",
    },
    "sysmon:13": {
        "event_id": "13",
        "title": "Registry Value Set",
        "event_source": "Sysmon",
        "category": "Registry",
        "why_it_matters": "Value modifications can reveal persistence and tampering, especially in autorun and service configuration locations.",
        "fields": ["Image", "TargetObject", "Details", "User"],
        "triage": ["Review autorun values and suspicious executable paths.", "Correlate with the process that modified the key."],
        "severity_hint": "medium",
        "false_positives": ["Software updates", "GPO changes"],
        "related_events": ["Sysmon 12", "Sysmon 1"],
        "sample_spl": "sourcetype=sysmon EventCode=13 TargetObject=*\\Run* | table _time,host,Image,TargetObject,Details",
    },
    "sysmon:15": {
        "event_id": "15",
        "title": "File Create Stream Hash",
        "event_source": "Sysmon",
        "category": "File Activity",
        "why_it_matters": "Alternate data streams and zone identifiers can assist with download and attachment handling investigations.",
        "fields": ["Image", "TargetFilename", "Hash", "Contents"],
        "triage": ["Review Zone.Identifier and downloaded file provenance.", "Correlate with browser/email client and file execution."],
        "severity_hint": "low",
        "false_positives": ["Normal browser downloads"],
        "related_events": ["Sysmon 11", "Sysmon 1"],
        "sample_spl": "sourcetype=sysmon EventCode=15 | table _time,host,Image,TargetFilename,Contents",
    },
    "sysmon:22": {
        "event_id": "22",
        "title": "DNS Query",
        "event_source": "Sysmon",
        "category": "DNS",
        "why_it_matters": "Maps process activity to DNS lookups. Useful for malware, phishing, C2, and suspicious script activity.",
        "fields": ["Image", "QueryName", "QueryStatus", "QueryResults", "User"],
        "triage": ["Review process making the DNS query.", "Correlate QueryName with outbound connections and user activity.", "Look for suspicious TLDs, newly observed domains, or random-looking names."],
        "severity_hint": "medium",
        "false_positives": ["Browser browsing", "Updater traffic"],
        "related_events": ["Sysmon 1", "Sysmon 3"],
        "sample_spl": "sourcetype=sysmon EventCode=22 | stats count by Image,QueryName | sort -count",
    },
}


# Additional local reference coverage for the SOC Guide identifier. These entries are
# intentionally concise; deeper investigation guidance can be expanded over time.
WINDOWS_EVENTS.update({
    "4616": {
        "title": "System Time Changed",
        "event_source": "Windows Security",
        "category": "System Integrity",
        "why_it_matters": "Time changes can affect log ordering, Kerberos, and forensic timelines. Unexpected changes can support evasion or misconfiguration review.",
        "fields": ["Previous Time", "New Time", "Process Name", "Subject Account Name"],
        "triage": ["Check whether the change came from time sync, admin action, or a suspicious process.", "Correlate with authentication failures and timeline gaps."],
        "severity_hint": "medium",
        "false_positives": ["NTP correction", "Admin maintenance", "VM clock sync"],
        "related_events": ["4624", "4688"],
        "sample_spl": "EventCode=4616 | table _time,host,Subject_Account_Name,Process_Name,Previous_Time,New_Time",
    },
    "4634": {
        "title": "Account Logged Off",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Completes logon-session timelines and helps measure session duration when paired with 4624.",
        "fields": ["Account Name", "Logon ID", "Logon Type"],
        "triage": ["Correlate by Logon ID with 4624 and 4672.", "Look for unusually long or short sessions for privileged users."],
        "severity_hint": "info",
        "false_positives": ["Normal user logoff", "Service session ending"],
        "related_events": ["4624", "4647", "4672"],
        "sample_spl": "EventCode=4634 | stats count by Account_Name,Logon_Type,host",
    },
    "4647": {
        "title": "User Initiated Logoff",
        "event_source": "Windows Security",
        "category": "Authentication",
        "why_it_matters": "Shows a user-initiated logoff and supports session reconstruction.",
        "fields": ["Account Name", "Logon ID"],
        "triage": ["Pair with 4624/4634 to reconstruct the session.", "Review unexpected privileged session endings."],
        "severity_hint": "info",
        "false_positives": ["Normal logoff"],
        "related_events": ["4624", "4634"],
        "sample_spl": "EventCode=4647 | table _time,host,Account_Name,Logon_ID",
    },
    "4656": {
        "title": "Handle Requested for Object",
        "event_source": "Windows Security",
        "category": "Object Access",
        "why_it_matters": "Object access pre-event that can support file, registry, or process access investigations when auditing is enabled.",
        "fields": ["Object Name", "Object Type", "Accesses", "Process Name", "Account Name"],
        "triage": ["Review sensitive object names and access rights.", "Correlate with 4663 for actual object access."],
        "severity_hint": "low",
        "false_positives": ["Normal object access auditing noise"],
        "related_events": ["4663", "4657"],
        "sample_spl": "EventCode=4656 | table _time,host,Account_Name,Object_Name,Object_Type,Accesses,Process_Name",
    },
    "4657": {
        "title": "Registry Value Modified",
        "event_source": "Windows Security",
        "category": "Registry",
        "why_it_matters": "Registry modification can reveal persistence, policy tampering, or configuration changes when auditing is enabled.",
        "fields": ["Object Name", "Value Name", "Process Name", "Old Value", "New Value"],
        "triage": ["Focus on Run keys, services, security products, and policy locations.", "Correlate with process creation and account context."],
        "severity_hint": "medium",
        "false_positives": ["Installer activity", "Group Policy updates"],
        "related_events": ["4688", "Sysmon 12", "Sysmon 13"],
        "sample_spl": "EventCode=4657 | table _time,host,Account_Name,Object_Name,Value_Name,Process_Name",
    },
    "4662": {
        "title": "Operation Performed on Object",
        "event_source": "Windows Security",
        "category": "Directory Service Access",
        "why_it_matters": "Useful for Active Directory object access review, including sensitive object or permission reads/modifications.",
        "fields": ["Object Name", "Object Type", "Properties", "Access Mask", "Subject Account Name"],
        "triage": ["Decode object GUIDs/properties where possible.", "Review privileged accounts and sensitive AD objects."],
        "severity_hint": "medium",
        "false_positives": ["Directory service auditing noise", "Admin tooling"],
        "related_events": ["4738", "4728", "4732"],
        "sample_spl": "EventCode=4662 | table _time,host,Subject_Account_Name,Object_Name,Object_Type,Properties",
    },
    "4663": {
        "title": "Attempt Made to Access an Object",
        "event_source": "Windows Security",
        "category": "Object Access",
        "why_it_matters": "Shows actual access to audited files, registry keys, or objects. Useful for sensitive file and share monitoring.",
        "fields": ["Object Name", "Accesses", "Process Name", "Account Name"],
        "triage": ["Review sensitive paths and access type.", "Correlate with share access 5140/5145 when network access is involved."],
        "severity_hint": "medium",
        "false_positives": ["Normal audited file access", "Backup/indexing tools"],
        "related_events": ["4656", "5140", "5145"],
        "sample_spl": "EventCode=4663 | table _time,host,Account_Name,Object_Name,Accesses,Process_Name",
    },
    "4699": {
        "title": "Scheduled Task Deleted",
        "event_source": "Windows Security",
        "category": "Persistence",
        "why_it_matters": "Task deletion can indicate cleanup after persistence or normal administration.",
        "fields": ["Task Name", "Subject Account Name"],
        "triage": ["Check whether the deleted task was recently created or modified.", "Review account and host context."],
        "severity_hint": "medium",
        "false_positives": ["Admin cleanup", "Software uninstall"],
        "related_events": ["4698", "4702", "4688"],
        "sample_spl": "EventCode=4699 | table _time,host,Subject_Account_Name,Task_Name",
    },
    "4719": {
        "title": "System Audit Policy Changed",
        "event_source": "Windows Security",
        "category": "Policy Change",
        "why_it_matters": "Audit policy changes can reduce visibility or indicate legitimate policy administration.",
        "fields": ["Subject Account Name", "Category", "Subcategory", "Changes"],
        "triage": ["Verify change ticket or GPO source.", "Review whether logging was weakened before/after suspicious activity."],
        "severity_hint": "high",
        "false_positives": ["GPO update", "Security baseline deployment"],
        "related_events": ["1102", "4902"],
        "sample_spl": "EventCode=4719 | table _time,host,Subject_Account_Name,Category,Subcategory,Changes",
    },
    "4723": {
        "title": "Password Change Attempt",
        "event_source": "Windows Security",
        "category": "Account Management",
        "why_it_matters": "Password change attempts help account takeover, helpdesk, and user lifecycle review.",
        "fields": ["Target Account Name", "Subject Account Name", "Status"],
        "triage": ["Review repeated failures or privileged targets.", "Correlate with 4625 and account lockouts."],
        "severity_hint": "medium",
        "false_positives": ["Normal user password change"],
        "related_events": ["4724", "4740", "4625"],
        "sample_spl": "EventCode=4723 | table _time,host,Subject_Account_Name,Target_Account_Name,Status",
    },
    "4724": {
        "title": "Password Reset Attempt",
        "event_source": "Windows Security",
        "category": "Account Management",
        "why_it_matters": "Password resets by another account are important for helpdesk abuse and account takeover review.",
        "fields": ["Target Account Name", "Subject Account Name", "Status"],
        "triage": ["Validate requester and reset source.", "Review privileged or service account resets."],
        "severity_hint": "high",
        "false_positives": ["Helpdesk password reset"],
        "related_events": ["4723", "4738", "4624"],
        "sample_spl": "EventCode=4724 | table _time,host,Subject_Account_Name,Target_Account_Name,Status",
    },
    "4725": {
        "title": "User Account Disabled",
        "event_source": "Windows Security",
        "category": "Account Management",
        "why_it_matters": "Account disable activity is useful for lifecycle, incident response, and potential admin abuse review.",
        "fields": ["Target Account Name", "Subject Account Name"],
        "triage": ["Confirm the disabling account and change context.", "Review unusual bulk disables."],
        "severity_hint": "medium",
        "false_positives": ["Offboarding", "Helpdesk action"],
        "related_events": ["4720", "4722", "4726"],
        "sample_spl": "EventCode=4725 | table _time,host,Subject_Account_Name,Target_Account_Name",
    },
    "4726": {
        "title": "User Account Deleted",
        "event_source": "Windows Security",
        "category": "Account Management",
        "why_it_matters": "Account deletion can be legitimate lifecycle activity or cleanup after abuse.",
        "fields": ["Target Account Name", "Subject Account Name"],
        "triage": ["Validate change ticket and actor.", "Look for create/enable/group-add activity before deletion."],
        "severity_hint": "high",
        "false_positives": ["Offboarding", "Admin cleanup"],
        "related_events": ["4720", "4722", "4728", "4732"],
        "sample_spl": "EventCode=4726 | table _time,host,Subject_Account_Name,Target_Account_Name",
    },
    "4729": {
        "title": "Member Removed from Security-Enabled Global Group",
        "event_source": "Windows Security",
        "category": "Group Management",
        "why_it_matters": "Group membership removal supports privilege and account lifecycle timelines.",
        "fields": ["Member Name", "Group Name", "Subject Account Name"],
        "triage": ["Review sensitive groups and actor context.", "Correlate with additions and account changes."],
        "severity_hint": "medium",
        "false_positives": ["Admin group cleanup"],
        "related_events": ["4728", "4732"],
        "sample_spl": "EventCode=4729 | table _time,host,Subject_Account_Name,Member_Name,Group_Name",
    },
    "4738": {
        "title": "User Account Changed",
        "event_source": "Windows Security",
        "category": "Account Management",
        "why_it_matters": "Account attribute changes can indicate lifecycle updates, tampering, or preparation for abuse.",
        "fields": ["Target Account Name", "Subject Account Name", "Changed Attributes"],
        "triage": ["Review changed attributes such as UAC flags, SPNs, delegation, and password settings.", "Correlate with group changes and logons."],
        "severity_hint": "medium",
        "false_positives": ["Normal admin change", "Directory sync"],
        "related_events": ["4720", "4722", "4725", "4728"],
        "sample_spl": "EventCode=4738 | table _time,host,Subject_Account_Name,Target_Account_Name,Changed_Attributes",
    },
    "4756": {
        "title": "Member Added to Universal Group",
        "event_source": "Windows Security",
        "category": "Group Management",
        "why_it_matters": "Membership additions to universal groups may grant broad access depending on AD design.",
        "fields": ["Member Name", "Group Name", "Subject Account Name"],
        "triage": ["Review whether the group is privileged or high-impact.", "Validate actor and ticket."],
        "severity_hint": "high",
        "false_positives": ["Admin group management"],
        "related_events": ["4728", "4732", "4672"],
        "sample_spl": "EventCode=4756 | table _time,host,Subject_Account_Name,Member_Name,Group_Name",
    },
    "4767": {
        "title": "User Account Unlocked",
        "event_source": "Windows Security",
        "category": "Account Management",
        "why_it_matters": "Unlocks after brute force or spraying can indicate recovery, helpdesk action, or attacker pressure.",
        "fields": ["Target Account Name", "Subject Account Name"],
        "triage": ["Check preceding 4740 and 4625 events.", "Validate who unlocked the account and from where."],
        "severity_hint": "medium",
        "false_positives": ["Helpdesk unlock"],
        "related_events": ["4740", "4625", "4724"],
        "sample_spl": "EventCode=4767 | table _time,host,Subject_Account_Name,Target_Account_Name",
    },
    "4778": {
        "title": "Session Reconnected to Window Station",
        "event_source": "Windows Security",
        "category": "Remote Access",
        "why_it_matters": "RDP session reconnection can support remote access and session timeline review.",
        "fields": ["Account Name", "Client Name", "Client Address", "Session Name"],
        "triage": ["Confirm source IP/client and user expectation.", "Correlate with 4624 type 10 and 4779 disconnects."],
        "severity_hint": "medium",
        "false_positives": ["Normal RDP reconnect"],
        "related_events": ["4624", "4779"],
        "sample_spl": "EventCode=4778 | table _time,host,Account_Name,Client_Name,Client_Address,Session_Name",
    },
    "4779": {
        "title": "Session Disconnected from Window Station",
        "event_source": "Windows Security",
        "category": "Remote Access",
        "why_it_matters": "RDP disconnect events help reconstruct interactive remote sessions.",
        "fields": ["Account Name", "Client Name", "Client Address", "Session Name"],
        "triage": ["Pair with 4778 and 4624 type 10.", "Review unusual remote session sources."],
        "severity_hint": "info",
        "false_positives": ["Normal RDP disconnect"],
        "related_events": ["4624", "4778"],
        "sample_spl": "EventCode=4779 | table _time,host,Account_Name,Client_Name,Client_Address,Session_Name",
    },
    "4902": {
        "title": "Per-User Audit Policy Table Created",
        "event_source": "Windows Security",
        "category": "Policy Change",
        "why_it_matters": "Audit policy table changes can support visibility and auditing investigations.",
        "fields": ["Subject Account Name", "User SID"],
        "triage": ["Validate policy source and actor.", "Correlate with other audit policy changes."],
        "severity_hint": "medium",
        "false_positives": ["GPO/security baseline activity"],
        "related_events": ["4719", "1102"],
        "sample_spl": "EventCode=4902 | table _time,host,Subject_Account_Name,User_SID",
    },
    "5024": {
        "title": "Windows Firewall Service Started",
        "event_source": "Windows Security",
        "category": "Firewall",
        "why_it_matters": "Firewall service state can support host hardening and tamper review.",
        "fields": ["Service Name", "Profile"],
        "triage": ["Check for unexpected stops/starts or policy changes.", "Correlate with firewall rule modifications."],
        "severity_hint": "info",
        "false_positives": ["System boot", "Policy refresh"],
        "related_events": ["4946", "4947", "5156", "5157"],
        "sample_spl": "EventCode=5024 | table _time,host,message",
    },
    "5156": {
        "title": "Windows Filtering Platform Allowed Connection",
        "event_source": "Windows Security",
        "category": "Firewall",
        "why_it_matters": "Allowed network connections can support endpoint network timelines when WFP auditing is enabled.",
        "fields": ["Application Name", "Source Address", "Destination Address", "Destination Port", "Protocol"],
        "triage": ["Focus on unusual applications, external destinations, or sensitive ports.", "Correlate with process creation and DNS."],
        "severity_hint": "low",
        "false_positives": ["High-volume normal network activity"],
        "related_events": ["5157", "Sysmon 3", "Sysmon 22"],
        "sample_spl": "EventCode=5156 | stats count by Application_Name,Destination_Address,Destination_Port",
    },
    "5157": {
        "title": "Windows Filtering Platform Blocked Connection",
        "event_source": "Windows Security",
        "category": "Firewall",
        "why_it_matters": "Blocked connections can indicate probing, policy enforcement, or suspicious applications attempting outbound access.",
        "fields": ["Application Name", "Source Address", "Destination Address", "Destination Port", "Protocol"],
        "triage": ["Review blocked destination and originating process.", "Look for repeated attempts or unusual ports."],
        "severity_hint": "medium",
        "false_positives": ["Normal firewall blocks", "Misconfigured apps"],
        "related_events": ["5156", "Sysmon 3"],
        "sample_spl": "EventCode=5157 | stats count by Application_Name,Destination_Address,Destination_Port | sort -count",
    },
})

SYSMON_EVENTS.update({
    "sysmon:2": {
        "event_id": "2", "title": "File Creation Time Changed", "event_source": "Sysmon", "category": "File Activity",
        "why_it_matters": "Timestamp changes can indicate timestomping, installer behavior, or file manipulation.",
        "fields": ["Image", "TargetFilename", "CreationUtcTime", "PreviousCreationUtcTime", "User"],
        "triage": ["Check whether the process normally changes timestamps.", "Correlate with file creation, process execution, and signer/hash context."],
        "severity_hint": "medium", "false_positives": ["Installers", "Backup/restore tools"], "related_events": ["Sysmon 1", "Sysmon 11"],
        "sample_spl": "sourcetype=sysmon EventCode=2 | table _time,host,Image,TargetFilename,CreationUtcTime,PreviousCreationUtcTime",
    },
    "sysmon:4": {
        "event_id": "4", "title": "Sysmon Service State Changed", "event_source": "Sysmon", "category": "Sensor Health",
        "why_it_matters": "Shows Sysmon service start/stop state and supports telemetry health review.",
        "fields": ["State", "Version", "SchemaVersion"],
        "triage": ["Review unexpected stops or configuration changes.", "Correlate with service control events and admin activity."],
        "severity_hint": "medium", "false_positives": ["System boot", "Sysmon update"], "related_events": ["7045", "7036", "Sysmon 16"],
        "sample_spl": "sourcetype=sysmon EventCode=4 | table _time,host,State,Version,SchemaVersion",
    },
    "sysmon:5": {
        "event_id": "5", "title": "Process Terminated", "event_source": "Sysmon", "category": "Process Monitoring",
        "why_it_matters": "Supports process lifetime and suspicious short-lived execution timelines.",
        "fields": ["Image", "ProcessGuid", "ProcessId", "User"],
        "triage": ["Pair with Sysmon 1 by ProcessGuid.", "Look for short-lived suspicious processes."],
        "severity_hint": "low", "false_positives": ["Normal process exit"], "related_events": ["Sysmon 1"],
        "sample_spl": "sourcetype=sysmon EventCode=5 | table _time,host,User,Image,ProcessGuid",
    },
    "sysmon:6": {
        "event_id": "6", "title": "Driver Loaded", "event_source": "Sysmon", "category": "Driver / Kernel",
        "why_it_matters": "Driver load telemetry can reveal kernel-mode components, unsigned drivers, or suspicious security tool interaction.",
        "fields": ["ImageLoaded", "Hashes", "Signed", "Signature"],
        "triage": ["Prioritize unsigned or rare drivers.", "Validate signer and file path."],
        "severity_hint": "high", "false_positives": ["Legitimate drivers", "Hardware/security updates"], "related_events": ["7045", "Sysmon 7"],
        "sample_spl": "sourcetype=sysmon EventCode=6 Signed=false | table _time,host,ImageLoaded,Signature,Hashes",
    },
    "sysmon:8": {
        "event_id": "8", "title": "CreateRemoteThread", "event_source": "Sysmon", "category": "Process Injection",
        "why_it_matters": "Remote thread creation can indicate injection, debugging, or security tooling.",
        "fields": ["SourceImage", "TargetImage", "StartAddress", "StartModule", "StartFunction"],
        "triage": ["Review target process sensitivity and source image reputation.", "Correlate with process access and module loads."],
        "severity_hint": "high", "false_positives": ["EDR/AV", "Debuggers", "Accessibility tools"], "related_events": ["Sysmon 1", "Sysmon 7", "Sysmon 10"],
        "sample_spl": "sourcetype=sysmon EventCode=8 | table _time,host,SourceImage,TargetImage,StartModule,StartFunction",
    },
    "sysmon:9": {
        "event_id": "9", "title": "RawAccessRead", "event_source": "Sysmon", "category": "Disk Access",
        "why_it_matters": "Raw disk access can be relevant to credential theft, disk tools, and forensic utilities.",
        "fields": ["Image", "Device", "User"],
        "triage": ["Validate whether the image is expected to access raw disk.", "Review admin context and tool legitimacy."],
        "severity_hint": "high", "false_positives": ["Backup tools", "Disk utilities", "EDR/forensics"], "related_events": ["Sysmon 1"],
        "sample_spl": "sourcetype=sysmon EventCode=9 | table _time,host,Image,Device,User",
    },
    "sysmon:14": {
        "event_id": "14", "title": "Registry Key/Value Renamed", "event_source": "Sysmon", "category": "Registry",
        "why_it_matters": "Registry rename events can support persistence and tampering investigations.",
        "fields": ["Image", "TargetObject", "NewName", "User"],
        "triage": ["Review autorun/security-sensitive locations.", "Correlate with value set and process creation events."],
        "severity_hint": "medium", "false_positives": ["Installer activity", "Admin tooling"], "related_events": ["Sysmon 12", "Sysmon 13"],
        "sample_spl": "sourcetype=sysmon EventCode=14 | table _time,host,Image,TargetObject,NewName",
    },
    "sysmon:16": {
        "event_id": "16", "title": "Sysmon Configuration Changed", "event_source": "Sysmon", "category": "Sensor Health",
        "why_it_matters": "Configuration changes affect visibility and can indicate tuning, update, or tampering.",
        "fields": ["Configuration", "ConfigurationFileHash"],
        "triage": ["Confirm authorized config deployment.", "Review whether coverage was reduced."],
        "severity_hint": "high", "false_positives": ["Planned Sysmon config update"], "related_events": ["Sysmon 4", "7045"],
        "sample_spl": "sourcetype=sysmon EventCode=16 | table _time,host,Configuration,ConfigurationFileHash",
    },
    "sysmon:17": {
        "event_id": "17", "title": "Pipe Created", "event_source": "Sysmon", "category": "Named Pipes",
        "why_it_matters": "Named pipes can support lateral movement tooling, IPC, and C2 frameworks.",
        "fields": ["PipeName", "Image", "User"],
        "triage": ["Look for rare or suspicious pipe names.", "Correlate with process and network activity."],
        "severity_hint": "medium", "false_positives": ["Normal Windows IPC", "Enterprise agents"], "related_events": ["Sysmon 18", "Sysmon 1"],
        "sample_spl": "sourcetype=sysmon EventCode=17 | stats count by PipeName,Image,host | sort -count",
    },
    "sysmon:18": {
        "event_id": "18", "title": "Pipe Connected", "event_source": "Sysmon", "category": "Named Pipes",
        "why_it_matters": "Pipe connection telemetry helps trace IPC relationships and some lateral movement tools.",
        "fields": ["PipeName", "Image", "User"],
        "triage": ["Correlate with pipe creation and parent process.", "Review unusual pipe names."],
        "severity_hint": "medium", "false_positives": ["Normal Windows IPC", "Management agents"], "related_events": ["Sysmon 17", "Sysmon 1"],
        "sample_spl": "sourcetype=sysmon EventCode=18 | stats count by PipeName,Image,host | sort -count",
    },
    "sysmon:19": {
        "event_id": "19", "title": "WMI Event Filter", "event_source": "Sysmon", "category": "WMI Persistence",
        "why_it_matters": "WMI filters can be part of permanent WMI event subscription persistence.",
        "fields": ["Name", "Query", "EventNamespace", "User"],
        "triage": ["Review filter query and creator.", "Correlate with WMI consumer and binding events."],
        "severity_hint": "high", "false_positives": ["Enterprise management tooling"], "related_events": ["Sysmon 20", "Sysmon 21"],
        "sample_spl": "sourcetype=sysmon EventCode=19 | table _time,host,User,Name,Query,EventNamespace",
    },
    "sysmon:20": {
        "event_id": "20", "title": "WMI Event Consumer", "event_source": "Sysmon", "category": "WMI Persistence",
        "why_it_matters": "WMI consumers define the action for WMI event subscriptions and can execute persistence payloads.",
        "fields": ["Name", "Type", "Destination", "User"],
        "triage": ["Inspect consumer destination/command.", "Correlate with filter and binding."],
        "severity_hint": "high", "false_positives": ["Management tooling"], "related_events": ["Sysmon 19", "Sysmon 21"],
        "sample_spl": "sourcetype=sysmon EventCode=20 | table _time,host,User,Name,Type,Destination",
    },
    "sysmon:21": {
        "event_id": "21", "title": "WMI Consumer To Filter Binding", "event_source": "Sysmon", "category": "WMI Persistence",
        "why_it_matters": "Binds WMI filters to consumers; important for WMI persistence detection.",
        "fields": ["Consumer", "Filter", "User"],
        "triage": ["Review paired filter and consumer.", "Validate whether enterprise management created it."],
        "severity_hint": "high", "false_positives": ["Management tooling"], "related_events": ["Sysmon 19", "Sysmon 20"],
        "sample_spl": "sourcetype=sysmon EventCode=21 | table _time,host,User,Consumer,Filter",
    },
    "sysmon:23": {
        "event_id": "23", "title": "File Delete", "event_source": "Sysmon", "category": "File Activity",
        "why_it_matters": "File delete telemetry can support cleanup, ransomware, or staging investigations when enabled.",
        "fields": ["Image", "TargetFilename", "Hashes", "User"],
        "triage": ["Review deleted paths and process responsible.", "Correlate with file creation and execution."],
        "severity_hint": "medium", "false_positives": ["Normal cleanup", "Installers"], "related_events": ["Sysmon 1", "Sysmon 11", "Sysmon 26"],
        "sample_spl": "sourcetype=sysmon EventCode=23 | table _time,host,Image,TargetFilename,Hashes,User",
    },
    "sysmon:24": {
        "event_id": "24", "title": "Clipboard Change", "event_source": "Sysmon", "category": "User Activity",
        "why_it_matters": "Clipboard events can support credential or data handling investigations if configured.",
        "fields": ["Image", "Session", "ClientInfo", "Archived"],
        "triage": ["Use carefully due to privacy and volume concerns.", "Review only where policy permits."],
        "severity_hint": "low", "false_positives": ["Normal user clipboard activity"], "related_events": ["Sysmon 1"],
        "sample_spl": "sourcetype=sysmon EventCode=24 | table _time,host,Image,Session,ClientInfo",
    },
    "sysmon:25": {
        "event_id": "25", "title": "Process Tampering", "event_source": "Sysmon", "category": "Defense Evasion",
        "why_it_matters": "Can indicate process hollowing or image tampering behavior depending on Sysmon version/configuration.",
        "fields": ["Image", "Type", "User"],
        "triage": ["Prioritize unusual process paths and unsigned binaries.", "Correlate with process creation, network, and file activity."],
        "severity_hint": "high", "false_positives": ["Security tools", "Packers/protectors"], "related_events": ["Sysmon 1", "Sysmon 7", "Sysmon 10"],
        "sample_spl": "sourcetype=sysmon EventCode=25 | table _time,host,Image,Type,User",
    },
    "sysmon:26": {
        "event_id": "26", "title": "File Delete Detected", "event_source": "Sysmon", "category": "File Activity",
        "why_it_matters": "Version-dependent file delete detection event used to observe deleted files without archiving content.",
        "fields": ["Image", "TargetFilename", "Hashes", "User"],
        "triage": ["Review process responsible and path sensitivity.", "Correlate with process and file creation events."],
        "severity_hint": "medium", "false_positives": ["Normal cleanup"], "related_events": ["Sysmon 23", "Sysmon 11"],
        "sample_spl": "sourcetype=sysmon EventCode=26 | table _time,host,Image,TargetFilename,Hashes,User",
    },
    "sysmon:27": {
        "event_id": "27", "title": "File Block Executable", "event_source": "Sysmon", "category": "File Blocking",
        "why_it_matters": "Shows executable file block events when Sysmon file block rules are configured.",
        "fields": ["Image", "TargetFilename", "Hashes", "User"],
        "triage": ["Review blocked executable path and creating process.", "Confirm policy match and user context."],
        "severity_hint": "medium", "false_positives": ["Policy test", "Admin tooling"], "related_events": ["Sysmon 1", "Sysmon 11"],
        "sample_spl": "sourcetype=sysmon EventCode=27 | table _time,host,Image,TargetFilename,Hashes,User",
    },
    "sysmon:28": {
        "event_id": "28", "title": "File Block Shredding", "event_source": "Sysmon", "category": "File Blocking",
        "why_it_matters": "Shows blocked file shredding behavior where Sysmon rules support this event.",
        "fields": ["Image", "TargetFilename", "User"],
        "triage": ["Review whether a process attempted destructive file operations.", "Correlate with ransomware-style behavior and file delete events."],
        "severity_hint": "high", "false_positives": ["Admin secure-delete tools"], "related_events": ["Sysmon 23", "Sysmon 26"],
        "sample_spl": "sourcetype=sysmon EventCode=28 | table _time,host,Image,TargetFilename,User",
    },
    "sysmon:29": {
        "event_id": "29", "title": "File Executable Detected", "event_source": "Sysmon", "category": "File Activity",
        "why_it_matters": "Version-dependent executable detection event that can support payload staging review.",
        "fields": ["Image", "TargetFilename", "Hashes", "User"],
        "triage": ["Review executable path, signer/hash, and creating process.", "Correlate with execution and network activity."],
        "severity_hint": "medium", "false_positives": ["Software installs", "Developer builds"], "related_events": ["Sysmon 1", "Sysmon 11"],
        "sample_spl": "sourcetype=sysmon EventCode=29 | table _time,host,Image,TargetFilename,Hashes,User",
    },
})

ALL_EVENTS = {**WINDOWS_EVENTS, **SYSMON_EVENTS}


def _normalize_event_id(event_id: str) -> str:
    clean = str(event_id or "").strip().lower().replace("event", "").replace("id", "").strip()
    if clean.startswith("sysmon"):
        digits = "".join(ch for ch in clean if ch.isdigit())
        return f"sysmon:{digits}" if digits else clean
    if clean.startswith("s") and clean[1:].isdigit():
        return f"sysmon:{clean[1:]}"
    return clean


def lookup_event(event_id: str) -> dict:
    clean = _normalize_event_id(event_id)
    event = ALL_EVENTS.get(clean)

    if not event:
        return {
            "found": False,
            "event_id": str(event_id).strip(),
            "message": "Event ID is not in the local BeyondLabs reference yet.",
            "suggestion": "Use the text analyzer to extract IDs from a full alert, or add this event to the local guide later."
        }

    display_id = event.get("event_id") if clean.startswith("sysmon:") else clean
    return {
        "found": True,
        "event_id": display_id,
        "lookup_key": clean,
        **event
    }


def list_events() -> list[dict]:
    rows = []
    for event_id, data in ALL_EVENTS.items():
        display_id = data.get("event_id") if event_id.startswith("sysmon:") else event_id
        rows.append({
            "event_id": display_id,
            "lookup_key": event_id,
            "title": data["title"],
            "event_source": data.get("event_source", "Windows"),
            "category": data["category"],
            "severity_hint": data["severity_hint"],
            "why_it_matters": data.get("why_it_matters", ""),
        })
    return sorted(rows, key=lambda item: (item["event_source"], int(item["event_id"]) if str(item["event_id"]).isdigit() else 99999))


def analyze_event_text(text: str) -> dict:
    lowered = text.lower()
    found = []
    seen = set()

    for event_id in WINDOWS_EVENTS:
        if event_id in text and event_id not in seen:
            found.append(lookup_event(event_id))
            seen.add(event_id)

    for key, data in SYSMON_EVENTS.items():
        sysmon_id = str(data.get("event_id"))
        markers = [f"sysmon {sysmon_id}", f"eventcode={sysmon_id}", f"event id {sysmon_id}", f"eventid:{sysmon_id}"]
        if any(marker in lowered for marker in markers) and key not in seen:
            found.append(lookup_event(key))
            seen.add(key)

    return {
        "events_found": found,
        "count": len(found),
        "note": "Detected known Windows/Sysmon Event IDs from the local BeyondLabs guide."
    }
