import { useMemo, useState } from "react";
import { Server, Globe2, Download } from "lucide-react";
import { DataTable } from "@/components/output";
import { Panel, Chip } from "@/components/soc";
import { useLocker } from "@/lib/locker";
import { toast } from "sonner";

interface NmapOutputProps {
  body: string;
  command: string;
  target: string;
  mode?: string;
  timing?: string;
  status: string;
}

function parseNmapPorts(stdout: string): { port: string; state: string; service: string }[] {
  const ports: { port: string; state: string; service: string }[] = [];
  const lines = stdout.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^\d+\/(tcp|udp)\s+/.test(trimmed)) {
      const parts = trimmed.split(/\s{2,}|\t+/);
      const [portProto, state, ...rest] = parts;
      const svc = parts.length >= 3 ? parts.slice(1).find((p) => /^[a-z]/.test(p)) || rest[0] || "" : "";
      ports.push({ port: portProto || trimmed, state: state || "unknown", service: svc || "" });
    }
  }
  return ports;
}

function portRiskTone(service: string): "destructive" | "warning" | "success" | "default" {
  const svc = service.toLowerCase().trim();
  if (["ssh", "telnet", "ftp", "rdp", "vnc", "mysql", "ms-sql", "oracle", "postgresql", "redis", "mongodb", "cassandra", "elasticsearch"].some((s) => svc.includes(s))) return "destructive";
  if (["http", "https", "apache", "nginx", "iis", "tomcat", "couchdb", "memcached", "smtp", "pop3", "imap"].some((s) => svc.includes(s))) return "warning";
  if (["dns", "ntp", "snmp", "dhcp", "ldap", "kerberos", "sip"].some((s) => svc.includes(s))) return "default";
  return "success";
}

function genMarkdownReport(target: string, stdout: string): string {
  const ports = parseNmapPorts(stdout);
  const ips = [...new Set(stdout.match(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g) || [])].filter((ip) => ip !== target && !ip.startsWith("127.") && !ip.startsWith("10.") && !ip.startsWith("192.168.") && !ip.startsWith("172."));
  const lines = [`# Nmap Scan: ${target}`, "", "## Open Ports", "", "| Port | State | Service |", "|------|-------|---------|", ...ports.map((p) => `| ${p.port} | ${p.state} | ${p.service} |`), "", ...(ips.length > 0 ? ["## Discovered IPs", "", ...ips.map((ip) => `- ${ip}`), ""] : []), "_Generated by BeyondLabs Hacking Toolkit_"];
  return lines.join("\n");
}

function genJsonExport(target: string, stdout: string): string {
  const ports = parseNmapPorts(stdout);
  const ips = [...new Set(stdout.match(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g) || [])].filter((ip) => ip !== target && !ip.startsWith("127.") && !ip.startsWith("10.") && !ip.startsWith("192.168.") && !ip.startsWith("172."));
  return JSON.stringify({ target, timestamp: new Date().toISOString(), ports, discoveredIps: ips, raw: stdout.length > 5000 ? stdout.slice(0, 5000) + "\n... truncated" : stdout }, null, 2);
}

export function NmapOutput({ body, command, target, status }: NmapOutputProps) {
  const locker = useLocker();
  const [copied, setCopied] = useState<string | null>(null);

  const ports = useMemo(() => parseNmapPorts(body), [body]);
  const ips = useMemo(() => {
    return [...new Set(body.match(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g) || [])]
      .filter((ip) => ip !== target && !ip.startsWith("127.") && !ip.startsWith("10.") && !ip.startsWith("192.168.") && !ip.startsWith("172."));
  }, [body, target]);

  const hasRichOutput = ports.length > 0 || ips.length > 0;

  if (!hasRichOutput) return null;

  return (
    <>
      {ports.length > 0 && (
        <Panel icon={Server} title="Port summary" meta={`${ports.length} open port(s)`}>
          <div className="mb-2 flex items-center gap-3 text-mono text-[10px] text-muted-foreground">
            <span className="flex items-center gap-1"><span className="inline-block h-2 w-2 rounded bg-destructive/60" /> danger</span>
            <span className="flex items-center gap-1"><span className="inline-block h-2 w-2 rounded bg-warning/60" /> web-exposed</span>
            <span className="flex items-center gap-1"><span className="inline-block h-2 w-2 rounded bg-success/60" /> trusted</span>
          </div>
          <DataTable
            columns={[
              { key: "port", label: "Port", align: "right", sortable: true, width: "80px", render: (p: any) => <span className="font-mono tabular-nums text-foreground/90">{p.port}</span> },
              { key: "state", label: "State", sortable: true, width: "100px", render: (p: any) => <Chip tone={p.state === "open" ? "destructive" : p.state === "filtered" ? "warning" : "default"}>{p.state}</Chip> },
              { key: "service", label: "Service", sortable: true, render: (p: any) => <span className="text-foreground/80">{p.service}</span> },
            ]}
            rows={ports.slice(0, 50)}
          />
        </Panel>
      )}

      {ips.length > 0 && (
        <Panel icon={Globe2} title="Discovered IPs" meta={`${ips.length} address(es)`} priority="secondary" actions={
          <button onClick={() => { ips.forEach((ip) => locker.add({ value: ip, type: "ipv4", source: "/hacking-toolkit" })); toast(`Added ${ips.length} IPs to locker`); }} className="inline-flex items-center gap-1 rounded border border-border/50 bg-card/40 px-2 py-0.5 text-mono text-[9px] uppercase tracking-widest text-muted-foreground hover:bg-card/70 hover:text-foreground">+ locker</button>
        }>
          <div className="flex flex-wrap gap-1.5">
            {ips.map((ip) => (
              <span key={ip} className="group inline-flex items-center gap-1 rounded border border-divider-strong bg-background/40 px-2 py-0.5 text-mono ba-text-sm text-foreground/90">
                {ip}
                <button onClick={() => locker.add({ value: ip, type: "ipv4", source: "/hacking-toolkit" })} className="rounded p-0.5 text-muted-foreground/60 opacity-0 transition-opacity hover:text-primary group-hover:opacity-100" title="add to locker">+</button>
              </span>
            ))}
          </div>
        </Panel>
      )}

      <Panel title="Export" meta="report" priority="secondary" collapsible storageKey="ba.panel.nmap.export" defaultCollapsed>
        <div className="flex flex-wrap gap-2">
          <button onClick={() => { const md = genMarkdownReport(target, body); const blob = new Blob([md], { type: "text/markdown" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `nmap-${target}-${Date.now()}.md`; a.click(); URL.revokeObjectURL(url); }} className="inline-flex items-center gap-1.5 rounded border border-primary/40 bg-primary/10 px-2.5 py-1.5 text-mono text-[10px] uppercase tracking-widest text-primary transition-all hover:bg-primary/20"><Download className="h-3 w-3" /> Markdown Report</button>
          <button onClick={() => { const json = genJsonExport(target, body); const blob = new Blob([json], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `nmap-${target}.json`; a.click(); URL.revokeObjectURL(url); }} className="inline-flex items-center gap-1.5 rounded border border-primary/40 bg-primary/10 px-2.5 py-1.5 text-mono text-[10px] uppercase tracking-widest text-primary transition-all hover:bg-primary/20"><Download className="h-3 w-3" /> JSON Export</button>
        </div>
      </Panel>
    </>
  );
}
