from app.services.tool_runner.knowledge import OFFENSIVE_KNOWLEDGE_DETAILS
from app.services.tool_runner.schemas import ToolDefinition, ToolProfile


def _profile(id: str, label: str, description: str) -> ToolProfile:
    return ToolProfile(id=id, label=label, description=description)


TOOL_DEFINITIONS: dict[str, ToolDefinition] = {
    "nmap": ToolDefinition(
        id="nmap",
        name="Nmap",
        group="Recon & Enumeration",
        kind="cli",
        cli_name="nmap",
        purpose="Authorized port and service enumeration for lab targets.",
        usage_note="Use only on owned, explicitly authorized, or isolated practice targets.",
        badges=["Active Tool", "Requires CLI", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[
            _profile("top100", "Top Ports", "TCP top-port sweep with service detection."),
            _profile("service", "Service Detection", "Basic service/version detection."),
            _profile("safe_scripts", "Safe NSE", "NSE safe scripts with service detection."),
        ],
        limitations=["No stealth scans, evasion flags, spoofing, or arbitrary Nmap arguments are exposed."],
        defender_artifacts=["Firewall denies/allows", "IDS port scan alerts", "NetFlow connection fan-out", "Host service logs"],
        detection_ideas=["Alert on many destination ports from one source in a short window.", "Correlate SYN fan-out with Nmap user-agent/script artifacts."],
        mitre_mapping=[{"technique_id": "T1046", "technique": "Network Service Discovery", "tactic": "Discovery"}],
        report_actions=["Save open ports, command preview, scope, and authorization note."],
    ),
    "whatweb": ToolDefinition(
        id="whatweb",
        name="WhatWeb",
        group="Recon & Enumeration",
        kind="cli",
        cli_name="whatweb",
        purpose="Identify web technologies on authorized sites.",
        usage_note="Run against owned lab sites or authorized targets only.",
        badges=["Active Tool", "Requires CLI", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[_profile("default", "Default", "Normal WhatWeb fingerprinting.")],
        limitations=["Aggressive WhatWeb modes are not exposed."],
        defender_artifacts=["Web server access logs", "User-Agent string", "TLS and proxy logs"],
        detection_ideas=["Look for unusual fingerprinting user-agents or broad virtual-host probing."],
        mitre_mapping=[{"technique_id": "T1595.002", "technique": "Vulnerability Scanning", "tactic": "Reconnaissance"}],
        report_actions=["Document technologies observed and confidence limits."],
    ),
    "gobuster-dir": ToolDefinition(
        id="gobuster-dir",
        name="Gobuster Directory Discovery",
        group="Recon & Enumeration",
        kind="cli",
        cli_name="gobuster",
        purpose="Directory discovery with a fixed wordlist path supplied by the analyst.",
        usage_note="Use only where directory brute-force testing is authorized.",
        badges=["Active Tool", "Advanced", "Requires CLI", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[_profile("dir", "Directory", "Gobuster dir mode with conservative threads.")],
        limitations=["Requires an existing local wordlist path; no built-in wordlist is bundled."],
        defender_artifacts=["HTTP 404/403/200 spikes", "Access logs", "WAF directory brute-force alerts"],
        detection_ideas=["Alert on high request rates across many paths with repeated 404 responses."],
        mitre_mapping=[{"technique_id": "T1595.002", "technique": "Vulnerability Scanning", "tactic": "Reconnaissance"}],
        report_actions=["Save discovered paths, status codes, rate, and wordlist name."],
    ),
    "ffuf-dir": ToolDefinition(
        id="ffuf-dir",
        name="ffuf Directory Discovery",
        group="Recon & Enumeration",
        kind="cli",
        cli_name="ffuf",
        purpose="Directory discovery using ffuf with fixed safe options.",
        usage_note="Use only for authorized web content discovery.",
        badges=["Active Tool", "Advanced", "Requires CLI", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[_profile("dir", "Directory", "ffuf URL FUZZ mode with conservative rate.")],
        limitations=["Requires an analyst-provided local wordlist path."],
        defender_artifacts=["HTTP status-code distribution", "WAF events", "Proxy logs"],
        detection_ideas=["Detect one source requesting many unique paths in a short window."],
        mitre_mapping=[{"technique_id": "T1595.002", "technique": "Vulnerability Scanning", "tactic": "Reconnaissance"}],
        report_actions=["Save discovered paths and filter assumptions."],
    ),
    "nikto": ToolDefinition(
        id="nikto",
        name="Nikto",
        group="Web Testing",
        kind="cli",
        cli_name="nikto",
        purpose="Authorized web server misconfiguration checks.",
        usage_note="Use only against owned or explicitly authorized web servers.",
        badges=["Active Tool", "Advanced", "Requires CLI", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[_profile("default", "Default", "Standard Nikto host check.")],
        limitations=["Nikto can be noisy; no evasion or tuning flags are exposed here."],
        defender_artifacts=["Web access logs", "IDS/WAF scan signatures", "Error spikes"],
        detection_ideas=["Correlate Nikto user-agent and known probe paths with server errors."],
        mitre_mapping=[{"technique_id": "T1595.002", "technique": "Vulnerability Scanning", "tactic": "Reconnaissance"}],
        report_actions=["Validate each finding manually before final report wording."],
    ),
    "nuclei": ToolDefinition(
        id="nuclei",
        name="Nuclei",
        group="Web Testing",
        kind="cli",
        cli_name="nuclei",
        purpose="Template-based authorized vulnerability checks.",
        usage_note="Run only with approved templates and written permission.",
        badges=["Active Tool", "Advanced", "Requires CLI", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[_profile("low", "Low Severity Templates", "Run low severity templates only.")],
        limitations=["Only low-severity template selection is exposed by default."],
        defender_artifacts=["HTTP scan patterns", "Template-specific request paths", "WAF/IDS events"],
        detection_ideas=["Track unusual template request bursts and vulnerability scanner user-agents."],
        mitre_mapping=[{"technique_id": "T1595.002", "technique": "Vulnerability Scanning", "tactic": "Reconnaissance"}],
        report_actions=["Include template IDs, severity, evidence, and validation status."],
    ),
    "sqlmap-lab": ToolDefinition(
        id="sqlmap-lab",
        name="sqlmap Lab Mode",
        group="Web Testing",
        kind="cli",
        cli_name="sqlmap",
        purpose="Authorized SQL injection lab checks with low-risk defaults.",
        usage_note="Use only on intentionally vulnerable labs or written-scope targets.",
        badges=["Active Tool", "Advanced", "Requires CLI", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[_profile("crawl0", "Single URL Check", "Batch mode, low risk/level, no dumping.")],
        limitations=["Database dumping, OS shell, tampering, and arbitrary flags are not exposed."],
        defender_artifacts=["Database errors", "WAF SQLi alerts", "Web access logs with payload parameters"],
        detection_ideas=["Alert on SQL meta-characters and time-delay probes in query parameters."],
        mitre_mapping=[{"technique_id": "T1190", "technique": "Exploit Public-Facing Application", "tactic": "Initial Access"}],
        report_actions=["Report only validated lab findings with request path, parameter, and limitations."],
    ),
    "john-audit": ToolDefinition(
        id="john-audit",
        name="John the Ripper Offline Audit",
        group="Password & Credential Lab",
        kind="cli",
        cli_name="john",
        purpose="Offline hash audit for owned lab hashes using analyst-supplied files.",
        usage_note="Only audit hashes you own or have explicit permission to test.",
        badges=["Active Tool", "Advanced", "Requires CLI", "Requires Authorization", "Report Ready"],
        profiles=[_profile("show", "Show Cracked", "Show already cracked hashes for a supplied file.")],
        limitations=["This lab does not attack live services and does not bundle wordlists."],
        defender_artifacts=["Endpoint process execution", "Credential audit records"],
        detection_ideas=["Detect password audit tools running outside approved admin windows."],
        mitre_mapping=[{"technique_id": "T1110.002", "technique": "Password Cracking", "tactic": "Credential Access"}],
        report_actions=["Save hash type, scope, cracking status, and remediation notes."],
    ),
    "hashcat-helper": ToolDefinition(
        id="hashcat-helper",
        name="Hashcat Helper",
        group="Password & Credential Lab",
        kind="knowledge",
        purpose="Explain safe hashcat mode selection and lab audit planning.",
        usage_note="Knowledge-only helper; it does not launch cracking jobs.",
        badges=["Knowledge Only", "Advanced", "Report Ready"],
        limitations=["No hashcat execution is performed by BeyondLabs."],
        defender_artifacts=["GPU workload, process execution, password audit artifacts"],
        detection_ideas=["Inventory approved password audit hosts and flag unexpected hashcat execution."],
        mitre_mapping=[{"technique_id": "T1110.002", "technique": "Password Cracking", "tactic": "Credential Access"}],
        report_actions=["Document authorization, hash source, and remediation guidance."],
    ),
    "hydra-lab": ToolDefinition(
        id="hydra-lab",
        name="Hydra Lab Mode",
        group="Password & Credential Lab",
        kind="knowledge",
        purpose="Teach live-service brute-force risk and detection without running attacks.",
        usage_note="Knowledge/demo-only in BeyondLabs; use isolated labs and explicit authorization.",
        badges=["Knowledge Only", "Advanced", "Requires Authorization", "Detection Available"],
        limitations=["Hydra is not executed because unrestricted live credential attacks are high-risk."],
        defender_artifacts=["Authentication failures", "Account lockouts", "Source IP reputation", "MFA prompts"],
        detection_ideas=["Alert on many failures per account/source and impossible travel after success."],
        mitre_mapping=[{"technique_id": "T1110", "technique": "Brute Force", "tactic": "Credential Access"}],
        report_actions=["Map failed-login evidence, thresholds, and response recommendations."],
    ),
    "metasploit-concepts": ToolDefinition(
        id="metasploit-concepts",
        name="Metasploit Concepts",
        group="Offensive Knowledge Base",
        kind="knowledge",
        purpose="Explain exploit module workflow, validation, and defender telemetry.",
        usage_note="Knowledge-only; BeyondLabs does not run exploit modules or payload handlers.",
        badges=["Knowledge Only", "Advanced", "Detection Available"],
        limitations=["No exploit or payload execution is provided."],
        defender_artifacts=["Exploit attempt logs", "EDR process/network telemetry", "IDS signatures"],
        detection_ideas=["Correlate exploit paths, abnormal child processes, and outbound callbacks."],
        mitre_mapping=[{"technique_id": "T1190", "technique": "Exploit Public-Facing Application", "tactic": "Initial Access"}],
        report_actions=["Describe lab module, evidence, and defensive observations without copying exploit steps."],
    ),
    "web-crawler": ToolDefinition(
        id="web-crawler",
        name="Web Crawler",
        group="Web Testing",
        kind="local",
        purpose="Safely crawl same-host HTML pages without JavaScript execution.",
        usage_note="Use only against authorized web apps; crawler is intentionally shallow.",
        badges=["Active Tool", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[_profile("default", "Shallow Crawl", "Fetch same-host HTML links up to a page limit.")],
        limitations=["No JavaScript execution, authentication, form submission, or recursive asset scraping."],
        defender_artifacts=["Access logs", "Proxy logs", "Crawl-like link traversal"],
        detection_ideas=["Detect repeated same-host crawling and unusual user-agent activity."],
        mitre_mapping=[{"technique_id": "T1595.002", "technique": "Vulnerability Scanning", "tactic": "Reconnaissance"}],
        report_actions=["Save crawled URLs, errors, and collection limits."],
    ),
    "secretfinder-js": ToolDefinition(
        id="secretfinder-js",
        name="JS/API Endpoint Discovery",
        group="Web Testing",
        kind="local",
        purpose="Find endpoint paths and secret-like candidates in pasted or fetched JavaScript.",
        usage_note="Treat candidate secrets as sensitive; validate ownership before use.",
        badges=["Active Tool", "Requires Authorization", "Detection Available", "Report Ready"],
        profiles=[_profile("default", "Endpoint Extract", "Extract endpoints and fingerprint secret-like strings.")],
        limitations=["Candidate secrets are fingerprinted and may be false positives."],
        defender_artifacts=["Static asset requests", "Secret scanning alerts", "Code review findings"],
        detection_ideas=["Monitor public JS for leaked tokens and exposed internal endpoints."],
        mitre_mapping=[{"technique_id": "T1592.002", "technique": "Software Discovery", "tactic": "Reconnaissance"}],
        report_actions=["Save endpoint list and secret candidate fingerprints, not raw secrets."],
    ),
    "wordlist-lab": ToolDefinition(
        id="wordlist-lab",
        name="Wordlist Generator / Analyzer",
        group="Password & Credential Lab",
        kind="local",
        purpose="Generate and analyze small lab wordlists from owned notes.",
        usage_note="For offline lab auditing and education only; not for live login attacks.",
        badges=["Active Tool", "Report Ready"],
        profiles=[_profile("default", "Generate", "Generate small variants from pasted seed text.")],
        limitations=["Does not run password attacks or test any service."],
        defender_artifacts=["Password audit planning records"],
        detection_ideas=["Use generated terms to improve banned-password and training guidance."],
        mitre_mapping=[{"technique_id": "T1110.002", "technique": "Password Cracking", "tactic": "Credential Access"}],
        report_actions=["Save wordlist assumptions and defensive password-policy notes."],
    ),
    "stego-lab": ToolDefinition(
        id="stego-lab",
        name="Steganography Lab",
        group="Network / Forensics",
        kind="local",
        purpose="Triage pasted stego-tool output and plan safe evidence handling.",
        usage_note="Does not decode or execute hidden payloads.",
        badges=["Active Tool", "Knowledge Only", "Report Ready"],
        profiles=[_profile("default", "Artifact Triage", "Extract stego workflow terms from pasted notes/output.")],
        limitations=["No file decoding is performed."],
        defender_artifacts=["Suspicious media metadata", "Archive signatures", "Outbound transfer logs"],
        detection_ideas=["Flag unusual polyglot files, metadata anomalies, and exfiltration channels."],
        mitre_mapping=[{"technique_id": "T1027", "technique": "Obfuscated Files or Information", "tactic": "Defense Evasion"}],
        report_actions=["Preserve hashes, metadata, tool output, and chain-of-custody notes."],
    ),
    "forensics-artifact-extractor": ToolDefinition(
        id="forensics-artifact-extractor",
        name="Forensics Artifact Extractor",
        group="Network / Forensics",
        kind="local",
        purpose="Extract common endpoint/browser artifact names from pasted notes.",
        usage_note="Pasted-text triage only; does not parse images or private databases.",
        badges=["Active Tool", "Detection Available", "Report Ready"],
        profiles=[_profile("default", "Artifact Terms", "Find common forensics artifact references.")],
        limitations=["No disk image parsing is performed."],
        defender_artifacts=["Prefetch, Amcache, ShimCache, browser history, LNK files"],
        detection_ideas=["Build timeline pivots from execution and browser artifacts."],
        mitre_mapping=[{"technique_id": "T1005", "technique": "Data from Local System", "tactic": "Collection"}],
        report_actions=["Save artifact terms and timeline questions."],
    ),
    "xss-sqli-helper": ToolDefinition(
        id="xss-sqli-helper",
        name="XSS / SQLi Lab Helper",
        group="Web Testing",
        kind="local",
        purpose="Identify lab payload patterns and convert them into detection notes.",
        usage_note="Pattern helper only; it does not send payloads.",
        badges=["Active Tool", "Detection Available", "Report Ready"],
        profiles=[_profile("default", "Pattern Triage", "Extract XSS and SQLi-like indicators from pasted requests/logs.")],
        limitations=["Pattern matches do not prove exploitability."],
        defender_artifacts=["Web access logs", "WAF events", "Application errors"],
        detection_ideas=["Alert on script tags, JavaScript protocol, SQL comments, UNION SELECT, and time-delay probes."],
        mitre_mapping=[{"technique_id": "T1190", "technique": "Exploit Public-Facing Application", "tactic": "Initial Access"}],
        report_actions=["Save request sample, matched indicators, and validation notes."],
    ),
    "payload-risk-workflow": ToolDefinition(
        id="payload-risk-workflow",
        name="Payload Risk Workflow",
        group="Controlled Workflows",
        kind="local",
        purpose="Build payload-behavior review, telemetry, and detection notes from pasted authorized lab context.",
        usage_note="Controlled local workflow; no payloads are generated or executed.",
        badges=["Active Tool", "Controlled", "Detection Available", "Report Ready"],
        profiles=[_profile("default", "Controlled Review", "Produce local review artifacts without payload generation.")],
        limitations=["No payload, shellcode, stager, droppers, or execution commands are generated."],
        defender_artifacts=["Process tree", "Command line", "Network callback", "File hash", "EDR alerts"],
        detection_ideas=["Detect interpreter abuse, encoded commands, child shells, and suspicious outbound callbacks."],
        mitre_mapping=[{"technique_id": "T1059", "technique": "Command and Scripting Interpreter", "tactic": "Execution"}],
        report_actions=["Save behavior summary, telemetry needs, and detection draft notes."],
    ),
    "exploit-risk-workflow": ToolDefinition(
        id="exploit-risk-workflow",
        name="Exploit Risk Workflow",
        group="Controlled Workflows",
        kind="local",
        purpose="Create non-destructive exploit validation and evidence-review artifacts from pasted scope notes.",
        usage_note="Controlled local workflow; no exploit code or payloads are generated.",
        badges=["Active Tool", "Controlled", "Report Ready"],
        profiles=[_profile("default", "Validation Review", "Produce evidence and validation checklists.")],
        limitations=["No exploit source, weaponized requests, or bypass steps are generated."],
        defender_artifacts=["Web access logs", "Application errors", "WAF events", "Patch inventory"],
        detection_ideas=["Correlate suspicious paths, error responses, exploit keywords, and scanner user agents."],
        mitre_mapping=[{"technique_id": "T1190", "technique": "Exploit Public-Facing Application", "tactic": "Initial Access"}],
        report_actions=["Document request path, parameter, non-destructive evidence, and limitation wording."],
    ),
    "reverse-shell-detection-workflow": ToolDefinition(
        id="reverse-shell-detection-workflow",
        name="Reverse Shell Detection Workflow",
        group="Controlled Workflows",
        kind="local",
        purpose="Turn suspected callback evidence into process/network pivots and detection notes.",
        usage_note="Controlled local workflow; no reverse shell payloads or listeners are generated.",
        badges=["Active Tool", "Controlled", "Detection Available"],
        profiles=[_profile("default", "Detection Review", "Extract callback indicators and pivots.")],
        limitations=["No reverse shell commands, payloads, or listener setup are generated."],
        defender_artifacts=["Child shell process", "Outbound connection", "DNS lookup", "Firewall log"],
        detection_ideas=["Detect shell spawned by web/process interpreters and unusual outbound callbacks."],
        mitre_mapping=[{"technique_id": "T1059", "technique": "Command and Scripting Interpreter", "tactic": "Execution"}],
        report_actions=["Save callback evidence, process lineage, and containment notes."],
    ),
    "malware-static-workflow": ToolDefinition(
        id="malware-static-workflow",
        name="Malware Static Workflow",
        group="Controlled Workflows",
        kind="local",
        purpose="Create a static malware triage plan from pasted strings, behavior notes, or scan context.",
        usage_note="Controlled local workflow; no malware is executed, detonated, or unpacked.",
        badges=["Active Tool", "Controlled", "Static Only", "Report Ready"],
        profiles=[_profile("default", "Static Triage", "Produce static analysis and reporting guidance.")],
        limitations=["No malware execution, detonation, macro execution, or unpacking is performed."],
        defender_artifacts=["Hashes", "Strings", "YARA hits", "Process and network IOCs"],
        detection_ideas=["Draft static YARA/Sigma logic from strings, LOLBins, persistence, and callback indicators."],
        mitre_mapping=[{"technique_id": "T1027", "technique": "Obfuscated Files or Information", "tactic": "Defense Evasion"}],
        report_actions=["Save static findings, extracted IOCs, and confidence limitations."],
    ),
    "credential-attack-detection-workflow": ToolDefinition(
        id="credential-attack-detection-workflow",
        name="Credential Attack Detection Workflow",
        group="Controlled Workflows",
        kind="local",
        purpose="Analyze pasted auth evidence for brute-force, stuffing, or spray detection logic.",
        usage_note="Controlled local workflow; no login attempts or online brute force are run.",
        badges=["Active Tool", "Controlled", "Detection Available", "Report Ready"],
        profiles=[_profile("default", "Auth Detection", "Generate thresholds, pivots, and test cases.")],
        limitations=["No Hydra, credential stuffing, password spraying, or live-service authentication attempts are executed."],
        defender_artifacts=["Failed logins", "Successful login after failures", "Account lockouts", "MFA prompts"],
        detection_ideas=["Alert on failures by source, username, target, and successful login after failures."],
        mitre_mapping=[{"technique_id": "T1110", "technique": "Brute Force", "tactic": "Credential Access"}],
        report_actions=["Save thresholds, affected users, source IPs, and response recommendations."],
    ),
    "stealth-evasion-detection-workflow": ToolDefinition(
        id="stealth-evasion-detection-workflow",
        name="Stealth / Evasion Detection Workflow",
        group="Controlled Workflows",
        kind="local",
        purpose="Review possible low-and-slow or evasion indicators and build defensive detection notes.",
        usage_note="Controlled local workflow; no stealth or evasion scan options are generated.",
        badges=["Active Tool", "Controlled", "Detection Available"],
        profiles=[_profile("default", "Detection Review", "Build defensive pivots and gap notes.")],
        limitations=["No decoys, spoofing, fragmentation, rate-evasion, or bypass commands are generated."],
        defender_artifacts=["NetFlow", "Firewall logs", "IDS alerts", "Proxy logs", "Scanner fingerprints"],
        detection_ideas=["Use rolling windows, source diversity, and service fan-out to detect low-rate probing."],
        mitre_mapping=[{"technique_id": "T1595", "technique": "Active Scanning", "tactic": "Reconnaissance"}],
        report_actions=["Save telemetry gaps, tuning notes, and validation steps."],
    ),
    "destructive-command-guardrail": ToolDefinition(
        id="destructive-command-guardrail",
        name="Destructive Command Guardrail",
        group="Controlled Workflows",
        kind="local",
        purpose="Classify pasted commands for destructive risk and produce containment/detection notes.",
        usage_note="Controlled local workflow; commands are never executed.",
        badges=["Active Tool", "Controlled", "Safety"],
        profiles=[_profile("default", "Risk Review", "Identify destructive command patterns.")],
        limitations=["No commands are executed or transformed into runnable destructive instructions."],
        defender_artifacts=["Shell history", "EDR process telemetry", "File deletion events", "Windows event logs"],
        detection_ideas=["Alert on bulk deletion, shadow copy removal, disk formatting, and log clearing commands."],
        mitre_mapping=[{"technique_id": "T1485", "technique": "Data Destruction", "tactic": "Impact"}],
        report_actions=["Save command evidence, host scope, containment steps, and validation limits."],
    ),
    "social-engineering-triage-workflow": ToolDefinition(
        id="social-engineering-triage-workflow",
        name="Social Engineering Triage Workflow",
        group="Controlled Workflows",
        kind="local",
        purpose="Turn pasted phishing/social engineering evidence into triage, controls, and report notes.",
        usage_note="Controlled local workflow; no phishing kits, messages, or credential capture are created.",
        badges=["Active Tool", "Controlled", "Report Ready"],
        profiles=[_profile("default", "Triage Review", "Extract pretext and reporting indicators.")],
        limitations=["No SET workflows, phishing kit generation, message sending, or credential collection are performed."],
        defender_artifacts=["Email headers", "URLs", "Attachment names", "User reports", "Mail gateway verdicts"],
        detection_ideas=["Detect credential-harvest language, sender mismatch, suspicious URLs, and attachment lures."],
        mitre_mapping=[{"technique_id": "T1566", "technique": "Phishing", "tactic": "Initial Access"}],
        report_actions=["Save pretext, indicators, user impact, and recommended containment actions."],
    ),
    "tshark-helper": ToolDefinition(
        id="tshark-helper",
        name="tshark / Wireshark Helper",
        group="Network / Forensics",
        kind="knowledge",
        purpose="Plan packet-analysis commands and detection pivots without reading arbitrary files.",
        usage_note="Use the existing PCAP analyzer for uploads; this helper is command-planning only.",
        badges=["Knowledge Only", "Detection Available", "Report Ready"],
        limitations=["No local PCAP path execution is exposed in this generic runner."],
        defender_artifacts=["DNS queries", "HTTP hosts", "TLS SNI", "beacon intervals"],
        detection_ideas=["Extract conversations, DNS rarity, HTTP paths, and periodic beaconing candidates."],
        mitre_mapping=[{"technique_id": "T1071", "technique": "Application Layer Protocol", "tactic": "Command and Control"}],
        report_actions=["Save filters, extracted IOCs, and beaconing confidence."],
    ),
}


KNOWLEDGE_TOPICS = [
    ("set-phishing-concepts", "SET / Phishing Concepts", "Social Engineering", "Knowledge-only overview of phishing pretexts, controls, and detection."),
    ("evilginx2-concepts", "Evilginx2 Concepts", "Social Engineering", "Knowledge-only discussion of adversary-in-the-middle phishing risks and defenses."),
    ("reverse-shells", "Reverse Shell Concepts", "Offensive Knowledge Base", "Concepts, lab safety, network artifacts, and detection ideas."),
    ("payload-creation", "Payload Creation Concepts", "Offensive Knowledge Base", "High-level payload lifecycle, safety boundaries, and defender telemetry."),
    ("post-exploitation", "Post-Exploitation Concepts", "Offensive Knowledge Base", "Conceptual post-exploitation phases and evidence artifacts."),
    ("ddos-concepts", "DDoS Concepts", "Offensive Knowledge Base", "Defensive understanding of volumetric/application DoS patterns."),
    ("rat-keylogger-concepts", "RAT / Keylogger Concepts", "Offensive Knowledge Base", "Defensive concepts for remote access malware and keylogging."),
    ("wireless-attack-concepts", "Wireless Attack Concepts", "Offensive Knowledge Base", "Wireless threat concepts and detection/hardening notes."),
    ("persistence-concepts", "Persistence Concepts", "Offensive Knowledge Base", "Common persistence ideas, artifacts, and cleanup/detection notes."),
    ("privilege-escalation-concepts", "Privilege Escalation Concepts", "Offensive Knowledge Base", "Privilege escalation concept map and defender artifacts."),
    ("credential-dumping-concepts", "Credential Dumping Concepts", "Offensive Knowledge Base", "Credential dumping risks, telemetry, and defensive controls."),
    ("c2-beaconing-concepts", "C2 / Beaconing Concepts", "Offensive Knowledge Base", "Beaconing behavior, network artifacts, and detection engineering notes."),
]

for topic_id, name, group, purpose in KNOWLEDGE_TOPICS:
    TOOL_DEFINITIONS[topic_id] = ToolDefinition(
        id=topic_id,
        name=name,
        group=group,
        kind="knowledge",
        purpose=purpose,
        usage_note="Knowledge-only entry for ethical lab understanding and detection writing; no offensive action is executed.",
        badges=["Knowledge Only", "Detection Available", "Report Ready"],
        limitations=["No commands, payloads, phishing kits, exploit modules, or abuse workflows are executed or generated."],
        defender_artifacts=["Logs and artifacts depend on the scenario; validate against lab evidence."],
        detection_ideas=["Convert observed lab behavior into evidence-backed Sigma/SIEM rules with false-positive notes."],
        mitre_mapping=[{"technique_id": "varies", "technique": "Scenario dependent", "tactic": "Varies"}],
        report_actions=["Document concept, lab scope, artifacts, detection logic, and limitations."],
    )

for tool_id, knowledge in OFFENSIVE_KNOWLEDGE_DETAILS.items():
    if tool_id in TOOL_DEFINITIONS:
        TOOL_DEFINITIONS[tool_id].knowledge = knowledge


def list_tools() -> list[dict]:
    return [tool.model_dump() for tool in TOOL_DEFINITIONS.values()]


def get_tool(tool_id: str) -> ToolDefinition | None:
    return TOOL_DEFINITIONS.get(tool_id)
