import { useEffect, useMemo, useRef, useState } from "react"
import {
  AlertTriangle,
  Check,
  ChevronDown,
  Clipboard,
  Database,
  Download,
  ExternalLink,
  HardDrive,
  Import,
  Info,
  Monitor,
  MonitorCog,
  Palette,
  RefreshCw,
  RotateCcw,
  Save,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Trash2,
  Upload,
  Wifi,
  WifiOff,
  Wrench,
} from "lucide-react"
import { copyText } from "../../lib/domUtils"
import { WorkbenchHeader, WorkbenchPage, WorkbenchPanel } from "../../components/layout/WorkbenchShell"
import { applyTheme, loadThemePreference, saveThemePreference, THEMES, THEME_STORAGE_KEY } from "../../lib/theme"
import {
  INVESTIGATION_SESSION_KEY,
  INVESTIGATION_STORAGE_MODE_KEY,
  INVESTIGATION_STORE_KEY,
  STORAGE_MODES,
  clearInvestigationData,
  exportInvestigationJson,
  getStorageMode,
  setStorageMode,
  storageCounts,
} from "../../lib/investigationStore"

const SETTINGS_KEY = "beyondarch_settings_v1"
const CYBERCHEF_RECIPE_KEY = "beyondarch_cyberchef_recipe_v1"
const CYBERCHEF_LAST_RECIPE_KEY = "beyondarch_cyberchef_last_recipe_v1"
const CYBERCHEF_FAVORITES_KEY = "beyondarch_cyberchef_favourites_v1"

const SECTIONS = [
  { id: "workspace", label: "Workspace", icon: Settings },
  { id: "privacy", label: "Privacy & Safety", icon: ShieldCheck },
  { id: "storage", label: "Storage & Backup", icon: Database },
  { id: "diagnostics", label: "Diagnostics", icon: Monitor },
  { id: "reset", label: "Reset", icon: RotateCcw },
]

const DEFAULT_SETTINGS = {
  version: 1,
  updatedAt: null,
  appearance: {
    theme: "light",
    accent: "cyan",
    density: "comfortable",
    reduceMotion: false,
  },
  general: {
    compactMode: false,
    showSampleButtons: true,
    confirmBeforeClearingInputs: true,
  },
  safety: {
    warnLargeInputs: true,
    warnLargeWordlists: true,
    defangMarkdownIocs: true,
  },
  backend: {
    apiUrl: "http://127.0.0.1:8000",
  },
}

const STORAGE_ITEMS = [
  {
    id: "settings",
    name: "Settings",
    description: "Theme, safety preferences, backend URL, and workspace behavior.",
    keys: [SETTINGS_KEY, THEME_STORAGE_KEY],
    exportable: true,
  },
  {
    id: "cyberchef-recipes",
    name: "CyberChef recipes",
    description: "Saved recipes, favorites, and local recipe state.",
    keys: [CYBERCHEF_RECIPE_KEY, CYBERCHEF_LAST_RECIPE_KEY, CYBERCHEF_FAVORITES_KEY],
    exportable: true,
  },
  {
    id: "workspace",
    name: "Workspace metadata",
    description: "Local cases, local intel, saved findings, and investigation notes where present.",
    keys: ["beyondarch_local_intel_v1", "beyondarch_cases_v1", "beyondarch_saved_findings_v1"],
    exportable: true,
  },
  {
    id: "module-outputs",
    name: "Module outputs",
    description: "Saved outputs, exports, and handoff artifacts generated by pages.",
    keys: ["beyondarch_module_outputs_v1", "beyondarch_exports_v1", "beyondarch.pendingArtifact"],
    exportable: true,
  },
  {
    id: "investigation-store",
    name: "Investigation store",
    description: "Shared artifacts, timeline, notes, hypotheses, findings, and report data controlled by the persistence setting.",
    keys: [INVESTIGATION_STORE_KEY, INVESTIGATION_SESSION_KEY, INVESTIGATION_STORAGE_MODE_KEY],
    exportable: true,
  },
]

const SAFETY_GUARANTEES = [
  "No automatic URL fetching",
  "No file execution or detonation",
  "No silent uploads of emails, logs, URLs, hashes, or files",
  "External reputation checks require explicit user action",
  "Active recon probes require authorization",
  "Detection and ATT&CK mappings remain analyst-validated candidates",
  "Attachment triage is static-first",
  "Local storage stays in the browser unless exported manually",
]

const ACTIVE_MODULES = [
  "Home",
  "CyberChef",
  "IDS Rule Builder",
  "SOC Analyst Playbook",
  "Smart Parser",
  "Phishing Triage",
  "Safe URL Analyzer",
  "Recon & Exposure",
  "SIEM",
  "Logs & Alerts",
  "Attachment Triage",
  "Detection & MITRE",
  "Settings",
]

function mergeSettings(raw = {}) {
  return {
    ...DEFAULT_SETTINGS,
    ...raw,
    appearance: { ...DEFAULT_SETTINGS.appearance, ...(raw.appearance || {}) },
    general: { ...DEFAULT_SETTINGS.general, ...(raw.general || {}) },
    safety: { ...DEFAULT_SETTINGS.safety, ...(raw.safety || {}) },
    backend: { ...DEFAULT_SETTINGS.backend, ...(raw.backend || {}) },
  }
}

function loadSettings() {
  try {
    const parsed = JSON.parse(localStorage.getItem(SETTINGS_KEY) || "null")
    return { settings: { ...mergeSettings(parsed || DEFAULT_SETTINGS), appearance: { ...mergeSettings(parsed || DEFAULT_SETTINGS).appearance, theme: loadThemePreference() } }, warning: "" }
  } catch {
    return {
      settings: { ...DEFAULT_SETTINGS, appearance: { ...DEFAULT_SETTINGS.appearance, theme: loadThemePreference() } },
      warning: "Stored settings were unreadable. Defaults are shown until you save again.",
    }
  }
}

function saveSettings(value) {
  const next = mergeSettings({ ...value, updatedAt: new Date().toISOString() })
  localStorage.setItem(SETTINGS_KEY, JSON.stringify(next))
  saveThemePreference(next.appearance.theme)
  return next
}

function applyUiPreferences(settings) {
  const root = document.documentElement
  root.dataset.density = settings.appearance.density
  root.dataset.accent = settings.appearance.accent
  root.dataset.motion = settings.appearance.reduceMotion ? "reduced" : "normal"
  root.classList.toggle("ba-compact-mode", Boolean(settings.general.compactMode))
}

function safeRead(key) {
  try {
    return localStorage.getItem(key)
  } catch {
    return null
  }
}

function roughSize(value = "") {
  const bytes = new Blob([value]).size
  if (bytes > 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(2)} MB`
  if (bytes > 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${bytes} B`
}

function storageSummary() {
  return STORAGE_ITEMS.map((item) => {
    const values = item.keys.map((key) => safeRead(key)).filter((value) => value !== null)
    const size = values.reduce((sum, value) => sum + new Blob([value]).size, 0)
    return { ...item, exists: values.length > 0, size: roughSize("x".repeat(size)), keyCount: values.length }
  })
}

function rawStorageRows() {
  return Object.keys(localStorage)
    .filter((key) => key.startsWith("beyondarch"))
    .sort()
    .map((key) => ({ key, size: roughSize(safeRead(key) || "") }))
}

function downloadJson(filename, payload) {
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}

function parseImport(text) {
  try {
    const parsed = JSON.parse(text)
    if (!parsed || typeof parsed !== "object") return { error: "Import must be a JSON object." }
    if (parsed.type !== "beyondarch_settings_export") return { error: "This is not a BeyondArch settings export." }
    if (!parsed.data || typeof parsed.data !== "object") return { error: "Export data is missing." }
    return { parsed }
  } catch (error) {
    return { error: `Invalid JSON: ${error.message}` }
  }
}

function normalizeBaseUrl(value) {
  return String(value || "http://127.0.0.1:8000").replace(/\/+$/, "")
}

function Button({ children, onClick, icon: Icon, variant = "secondary", disabled = false, className = "" }) {
  const styles = {
    primary: "ba-button-primary",
    secondary: "ba-button-secondary",
    ghost: "ba-button-ghost",
    danger: "border border-rose-500/40 bg-rose-500/12 text-rose-100 hover:bg-rose-500/18",
  }
  return (
    <button type="button" className={`${styles[variant] || styles.secondary} rounded-xl px-3 py-2 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-50 ${className}`} onClick={onClick} disabled={disabled}>
      {Icon && <Icon className="mr-2 inline h-4 w-4" />}
      {children}
    </button>
  )
}

function SectionNavButton({ active, children, onClick }) {
  return (
    <button type="button" onClick={onClick} className={`rounded-full border px-4 py-2 text-sm font-black transition ${active ? "border-cyan-400/50 bg-cyan-500/15 text-cyan-100" : "border-white/10 bg-black/40 text-zinc-300 hover:border-white/10 hover:text-zinc-100"}`}>
      {children}
    </button>
  )
}

function StatusPill({ children, tone = "info" }) {
  const colors = {
    info: "border-cyan-500/25 bg-cyan-500/10 text-cyan-100",
    ready: "border-emerald-500/25 bg-emerald-500/10 text-emerald-100",
    warning: "border-amber-500/30 bg-amber-500/10 text-amber-100",
    danger: "border-rose-500/30 bg-rose-500/10 text-rose-100",
    empty: "border-white/10 bg-black/40 text-zinc-300",
  }
  return <span className={`rounded-full border px-2 py-1 text-xs font-black uppercase tracking-[0.12em] ${colors[tone] || colors.info}`}>{children}</span>
}

function SectionTitle({ title, subtitle, icon: Icon }) {
  return (
    <div className="flex items-start gap-3">
      {Icon && <span className="rounded-xl border border-cyan-500/25 bg-cyan-500/10 p-2 text-cyan-200"><Icon className="h-4 w-4" /></span>}
      <div>
        <h2 className="text-lg font-black text-zinc-100">{title}</h2>
        {subtitle && <p className="mt-1 text-sm leading-6 text-zinc-400">{subtitle}</p>}
      </div>
    </div>
  )
}

function SettingToggle({ label, description, checked, onChange }) {
  return (
    <label className="flex items-start justify-between gap-4 rounded-xl border border-white/10 bg-black/40 p-3">
      <span>
        <span className="block text-sm font-bold text-zinc-100">{label}</span>
        {description && <span className="mt-1 block text-xs leading-5 text-zinc-400">{description}</span>}
      </span>
      <input className="mt-1 h-5 w-5 accent-cyan-400" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />
    </label>
  )
}

function SelectField({ label, description, value, options, onChange }) {
  const [open, setOpen] = useState(false)
  const [activeIndex, setActiveIndex] = useState(0)
  const ref = useRef(null)
  const selectedIndex = Math.max(0, options.findIndex((option) => option.value === value))
  const selected = options[selectedIndex] || options[0]

  useEffect(() => {
    if (!open) return undefined
    function closeOnOutside(event) {
      if (ref.current && !ref.current.contains(event.target)) setOpen(false)
    }
    document.addEventListener("pointerdown", closeOnOutside)
    return () => document.removeEventListener("pointerdown", closeOnOutside)
  }, [open])

  function choose(option) {
    onChange(option.value)
    setOpen(false)
  }

  function handleKeyDown(event) {
    if (event.key === "Escape") setOpen(false)
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault()
      if (!open) setOpen(true)
      else choose(options[activeIndex])
    }
    if (event.key === "ArrowDown" || event.key === "ArrowUp") {
      event.preventDefault()
      if (!open) setOpen(true)
      else setActiveIndex((current) => (current + (event.key === "ArrowDown" ? 1 : -1) + options.length) % options.length)
    }
  }

  return (
    <div className="relative rounded-xl border border-white/10 bg-black/40 p-3" ref={ref}>
      <span className="block text-sm font-bold text-zinc-100">{label}</span>
      {description && <span className="mt-1 block text-xs leading-5 text-zinc-400">{description}</span>}
      <button type="button" className="mt-2 flex w-full items-center justify-between rounded-lg border border-white/10 bg-black/50 px-3 py-2 text-left text-sm text-zinc-100 outline-none focus:border-cyan-400" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((value) => !value)} onKeyDown={handleKeyDown}>
        <span>
          <span className="block font-bold">{selected?.label}</span>
          {selected?.description && <span className="block text-xs text-zinc-400">{selected.description}</span>}
        </span>
        <ChevronDown className={`h-4 w-4 text-zinc-400 transition ${open ?"rotate-180" : ""}`} />
      </button>
      {open && (
        <div className="absolute left-3 right-3 top-[calc(100%-0.5rem)] z-30 overflow-hidden rounded-xl border border-white/10 bg-black/40 shadow-2xl" role="listbox">
          {options.map((option, index) => (
            <button key={option.value} type="button" role="option" aria-selected={option.value === value} className={`flex w-full items-start justify-between gap-3 px-3 py-2 text-left text-sm transition ${index === activeIndex ? "bg-cyan-500/15 text-cyan-100" : "text-zinc-200 hover:bg-black/40"}`} onMouseEnter={() => setActiveIndex(index)} onClick={() => choose(option)}>
              <span>
                <span className="block font-bold">{option.label}</span>
                {option.description && <span className="block text-xs text-zinc-400">{option.description}</span>}
              </span>
              {option.value === value && <Check className="mt-0.5 h-4 w-4 text-cyan-300" />}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

function StorageCard({ item, onClear }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-black/40 p-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="text-sm font-black text-zinc-100">{item.name}</h3>
          <p className="mt-1 text-xs leading-5 text-zinc-400">{item.description}</p>
        </div>
        <StatusPill tone={item.exists ? "ready" : "empty"}>{item.exists ? "Saved" : "Empty"}</StatusPill>
      </div>
      <div className="mt-3 grid grid-cols-2 gap-2 text-xs">
        <div className="rounded-xl border border-white/10 bg-black/30 p-2">
          <p className="uppercase tracking-[0.14em] text-zinc-500">Size</p>
          <p className="mt-1 font-bold text-zinc-200">{item.size}</p>
        </div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-2">
          <p className="uppercase tracking-[0.14em] text-zinc-500">Keys</p>
          <p className="mt-1 font-bold text-zinc-200">{item.keyCount}</p>
        </div>
      </div>
      <div className="mt-3">
        <Button icon={Trash2} variant="ghost" disabled={!item.exists} onClick={() => onClear(item)}>Clear</Button>
      </div>
    </div>
  )
}

export default function SettingsPage() {
  const initial = useMemo(() => loadSettings(), [])
  const [draft, setDraft] = useState(initial.settings)
  const [savedSnapshot, setSavedSnapshot] = useState(initial.settings)
  const [activeSection, setActiveSection] = useState("workspace")
  const [notice, setNotice] = useState(initial.warning)
  const [rows, setRows] = useState(() => storageSummary())
  const [rawRows, setRawRows] = useState(() => rawStorageRows())
  const [importText, setImportText] = useState("")
  const [importPreview, setImportPreview] = useState(null)
  const [investigationMode, setInvestigationMode] = useState(() => getStorageMode())
  const [investigationCounts, setInvestigationCounts] = useState(() => storageCounts())
  const [backendStatus, setBackendStatus] = useState({ label: "Not checked", tone: "empty", detail: "Run a health check against the configured local API." })
  const [checkingBackend, setCheckingBackend] = useState(false)
  const importFileRef = useRef(null)

  const dirty = useMemo(() => JSON.stringify(draft) !== JSON.stringify(savedSnapshot), [draft, savedSnapshot])

  useEffect(() => {
    applyTheme(draft.appearance.theme)
    applyUiPreferences(draft)
  }, [draft])

  function refreshStorage() {
    setRows(storageSummary())
    setRawRows(rawStorageRows())
    setInvestigationMode(getStorageMode())
    setInvestigationCounts(storageCounts())
  }

  function updateDraft(section, key, value) {
    setDraft((current) => ({
      ...current,
      [section]: { ...current[section], [key]: value },
    }))
  }

  function saveDraft() {
    const next = saveSettings(draft)
    setDraft(next)
    setSavedSnapshot(next)
    refreshStorage()
    setNotice("Settings saved locally.")
  }

  function discardDraft() {
    setDraft(savedSnapshot)
    applyTheme(savedSnapshot.appearance.theme)
    applyUiPreferences(savedSnapshot)
    setNotice("Unsaved settings were discarded.")
  }

  function clearKeys(item) {
    if (!window.confirm(`Clear ${item.name}? This cannot be undone.`)) return
    item.keys.forEach((key) => localStorage.removeItem(key))
    refreshStorage()
    setNotice(`${item.name} cleared.`)
  }

  function resetSettings() {
    if (!window.confirm("Reset settings to BeyondArch defaults?")) return
    saveThemePreference("light")
    const next = saveSettings(DEFAULT_SETTINGS)
    setDraft(next)
    setSavedSnapshot(next)
    refreshStorage()
    setNotice("Settings reset to defaults.")
  }

  function clearCyberChef() {
    if (!window.confirm("Clear CyberChef recipes, favorites, and last recipe?")) return
    ;[CYBERCHEF_RECIPE_KEY, CYBERCHEF_LAST_RECIPE_KEY, CYBERCHEF_FAVORITES_KEY].forEach((key) => localStorage.removeItem(key))
    refreshStorage()
    setNotice("CyberChef local data cleared.")
  }

  function clearWorkspace() {
    if (!window.confirm("Clear workspace metadata and saved module outputs?")) return
    ;["beyondarch_local_intel_v1", "beyondarch_cases_v1", "beyondarch_saved_findings_v1", "beyondarch_module_outputs_v1", "beyondarch_exports_v1", "beyondarch.pendingArtifact"].forEach((key) => localStorage.removeItem(key))
    clearInvestigationData()
    refreshStorage()
    setNotice("Workspace metadata, investigation store, and module outputs cleared.")
  }

  function clearAll() {
    if (!window.confirm("Clear all BeyondArch local data? This removes preferences, recipes, metadata, handoffs, and saved outputs.")) return
    Object.keys(localStorage).filter((key) => key.startsWith("beyondarch")).forEach((key) => localStorage.removeItem(key))
    saveThemePreference("light")
    const next = saveSettings(DEFAULT_SETTINGS)
    setDraft(next)
    setSavedSnapshot(next)
    refreshStorage()
    setNotice("All BeyondArch local data cleared and defaults restored.")
  }

  function exportPayload(mode) {
    if (mode === "investigation") {
      downloadJson("beyondarch-investigation-case.json", exportInvestigationJson())
      setNotice("Investigation case export created.")
      return
    }
    const keys = mode === "settings"
      ? [SETTINGS_KEY, THEME_STORAGE_KEY]
      : STORAGE_ITEMS.flatMap((item) => item.exportable ? item.keys : [])
    const data = {}
    keys.forEach((key) => {
      const raw = safeRead(key)
      if (raw === null) return
      try {
        data[key] = key === THEME_STORAGE_KEY ? raw : JSON.parse(raw)
      } catch {
        data[key] = raw
      }
    })
    downloadJson(`beyondarch-${mode}.json`, {
      type: "beyondarch_settings_export",
      version: 1,
      exportedAt: new Date().toISOString(),
      mode,
      warning: "Export may contain local analyst notes, saved artifacts, or module outputs. Review before sharing.",
      data,
    })
    setNotice(`${mode === "settings" ? "Settings" : "Local data"} export created.`)
  }

  function previewImport() {
    const result = parseImport(importText)
    if (result.error) {
      setImportPreview(null)
      setNotice(result.error)
      return
    }
    setImportPreview(result.parsed)
    setNotice(`Import preview ready: ${Object.keys(result.parsed.data).length} stored item(s) detected.`)
  }

  async function importFromFile(event) {
    const file = event.target.files?.[0]
    if (!file) return
    const text = await file.text()
    setImportText(text)
    setImportPreview(null)
    setNotice(`${file.name} loaded. Preview before applying.`)
    event.target.value = ""
  }

  function applyImport() {
    if (!importPreview) return
    if (!window.confirm("Apply imported BeyondArch data? Matching local values may be overwritten.")) return
    Object.entries(importPreview.data).forEach(([key, value]) => {
      if (key === THEME_STORAGE_KEY) {
        localStorage.setItem(key, String(value))
        saveThemePreference(String(value))
      } else {
        localStorage.setItem(key, typeof value === "string" ? value : JSON.stringify(value))
      }
    })
    const next = loadSettings().settings
    setDraft(next)
    setSavedSnapshot(next)
    setImportPreview(null)
    refreshStorage()
    setNotice("Import applied locally.")
  }

  async function checkBackend() {
    const base = normalizeBaseUrl(draft.backend.apiUrl)
    setCheckingBackend(true)
    setBackendStatus({ label: "Checking...", tone: "warning", detail: `GET ${base}/health` })
    try {
      const started = performance.now()
      const response = await fetch(`${base}/health`, { method: "GET" })
      const elapsed = Math.round(performance.now() - started)
      if (response.ok) {
        setBackendStatus({ label: "Online", tone: "ready", detail: `Health endpoint responded in ${elapsed} ms.` })
      } else {
        setBackendStatus({ label: `HTTP ${response.status}`, tone: "warning", detail: `Backend responded, but /health returned ${response.status}.` })
      }
    } catch {
      setBackendStatus({ label: "Offline", tone: "danger", detail: "Could not reach the local backend. Check run-beyondarch.zsh or uvicorn." })
    } finally {
      setCheckingBackend(false)
    }
  }

  function refreshDiagnostics() {
    refreshStorage()
    checkBackend()
  }

  function openApiDocs() {
    window.open(`${normalizeBaseUrl(draft.backend.apiUrl)}/docs`, "_blank", "noopener,noreferrer")
  }

  const totalStorage = roughSize(Object.keys(localStorage).reduce((acc, key) => acc + key + (safeRead(key) || ""), ""))
  const savedRows = rows.filter((row) => row.exists).length
  const backendBase = normalizeBaseUrl(draft.backend.apiUrl)

  return (
    <WorkbenchPage className="ba-settings-page">
      <WorkbenchHeader
        eyebrow="Settings"
        title="Settings Console"
        subtitle="Control appearance, safety defaults, local storage, backend diagnostics, and reset actions from one compact workspace."
        icon={MonitorCog}
        chips={[
          { label: "Local-first", tone: "success" },
          { label: `${savedRows}/${rows.length} storage groups saved`, tone: savedRows ? "warning" : "muted" },
          { label: dirty ? "Unsaved changes" : "Saved", tone: dirty ? "warning" : "success" },
        ]}
        actions={(
          <div className="flex flex-wrap gap-2">
            <Button icon={RotateCcw} disabled={!dirty} onClick={discardDraft}>Discard</Button>
            <Button icon={Save} variant="primary" disabled={!dirty} onClick={saveDraft}>Save settings</Button>
          </div>
        )}
      />

      {notice && (
        <WorkbenchPanel soft className="flex items-start gap-3">
          <Info className="mt-0.5 h-4 w-4 text-cyan-300" />
          <p className="text-sm text-zinc-200">{notice}</p>
        </WorkbenchPanel>
      )}

      <div className="flex flex-wrap gap-2">
        {SECTIONS.map((section) => (
          <SectionNavButton key={section.id} active={activeSection === section.id} onClick={() => setActiveSection(section.id)}>
            {section.icon && <section.icon className="mr-1.5 inline h-4 w-4" />}{section.label}
          </SectionNavButton>
        ))}
      </div>

      {activeSection === "workspace" && (
        <div className="grid gap-4 xl:grid-cols-[1.05fr_0.95fr]">
          <WorkbenchPanel className="space-y-4">
            <SectionTitle title="Appearance" subtitle="These controls affect the local browser UI only." icon={Palette} />
            <div className="grid gap-3 md:grid-cols-2">
              <SelectField label="Theme" value={draft.appearance.theme} options={[
                { label: `☀️ ${THEMES.light.label}`, value: "light", description: THEMES.light.description },
                { label: `🌙 ${THEMES.dark.label}`, value: "dark", description: THEMES.dark.description },
              ]} onChange={(value) => updateDraft("appearance", "theme", value)} />
              <SelectField label="Accent" value={draft.appearance.accent} options={[
                { label: "Cyan primary", value: "cyan", description: "Default BeyondArch SOC accent." },
                { label: "Violet secondary", value: "violet", description: "Slightly more purple highlight treatment." },
              ]} onChange={(value) => updateDraft("appearance", "accent", value)} />
              <SelectField label="Density" value={draft.appearance.density} options={[
                { label: "Comfortable", value: "comfortable", description: "More breathing room for long sessions." },
                { label: "Compact", value: "compact", description: "Denser tables and controls where supported." },
              ]} onChange={(value) => updateDraft("appearance", "density", value)} />
              <SettingToggle label="Reduce motion" description="Prefer fewer transitions and animated effects." checked={draft.appearance.reduceMotion} onChange={(value) => updateDraft("appearance", "reduceMotion", value)} />
            </div>
          </WorkbenchPanel>

          <WorkbenchPanel className="space-y-4">
            <SectionTitle title="Workspace behavior" subtitle="Preferences for repeated analyst workflows. Modules adopt these where implemented." icon={SlidersHorizontal} />
            <div className="grid gap-3">
              <SettingToggle label="Compact mode preference" description="Request denser page layouts where supported." checked={draft.general.compactMode} onChange={(value) => updateDraft("general", "compactMode", value)} />
              <SettingToggle label="Show sample shortcuts" description="Keep sample/demo buttons visible on tools that support them." checked={draft.general.showSampleButtons} onChange={(value) => updateDraft("general", "showSampleButtons", value)} />
              <SettingToggle label="Confirm before clearing inputs" description="Require confirmation before destructive clear actions where supported." checked={draft.general.confirmBeforeClearingInputs} onChange={(value) => updateDraft("general", "confirmBeforeClearingInputs", value)} />
            </div>
          </WorkbenchPanel>
        </div>
      )}

      {activeSection === "privacy" && (
        <div className="grid gap-4 xl:grid-cols-[1fr_0.85fr]">
          <WorkbenchPanel className="space-y-4">
            <SectionTitle title="Investigation data persistence" subtitle="Controls whether analyzed artifacts, notes, hypotheses, findings, and timeline events are restored after navigation or browser restart." icon={Database} />
            <div className="grid gap-3">
              {STORAGE_MODES.map((mode) => (
                <button
                  key={mode.value}
                  type="button"
                  className={`ba-storage-mode-card ${investigationMode === mode.value ? "is-active" : ""}`}
                  onClick={() => {
                    const next = setStorageMode(mode.value)
                    setInvestigationMode(next)
                    setInvestigationCounts(storageCounts())
                    refreshStorage()
                    setNotice(`Investigation persistence set to: ${mode.label}`)
                  }}
                >
                  <span><strong>{mode.label}</strong><small>{mode.description}</small></span>
                  <StatusPill tone={investigationMode === mode.value ? "ready" : "empty"}>{investigationMode === mode.value ? "Active" : "Option"}</StatusPill>
                </button>
              ))}
            </div>
            <div className="ba-investigation-counts">
              {Object.entries(investigationCounts).map(([key, value]) => <span key={key}>{key}: <strong>{value}</strong></span>)}
            </div>
            <div className="flex flex-wrap gap-2">
              <Button icon={Download} onClick={() => exportPayload("investigation")}>Export investigation case</Button>
              <Button icon={Trash2} variant="danger" onClick={() => { if (window.confirm("Clear investigation artifacts, timeline, notes, hypotheses, and findings?")) { clearInvestigationData(); refreshStorage(); setNotice("Investigation data cleared.") } }}>Clear investigation data</Button>
            </div>
          </WorkbenchPanel>
          <WorkbenchPanel className="space-y-4">
            <SectionTitle title="Safety model" subtitle="BeyondArch should stay explicit, local-first, and analyst-controlled." icon={ShieldCheck} />
            <div className="grid gap-3 md:grid-cols-2">
              {SAFETY_GUARANTEES.map((item) => (
                <div key={item} className="rounded-xl border border-white/10 bg-black/40 p-3 text-sm font-semibold text-zinc-100">
                  <ShieldCheck className="mr-2 inline h-4 w-4 text-emerald-300" />{item}
                </div>
              ))}
            </div>
          </WorkbenchPanel>
          <WorkbenchPanel className="space-y-4">
            <SectionTitle title="Editable safety defaults" subtitle="These preferences guide modules that support safety prompts and copied output formatting." icon={Wrench} />
            <SettingToggle label="Warn before large pasted inputs" description="Useful before parsing very large logs, emails, or IOC lists." checked={draft.safety.warnLargeInputs} onChange={(value) => updateDraft("safety", "warnLargeInputs", value)} />
            <SettingToggle label="Warn before large wordlists" description="Useful for recon helpers or local tool inputs." checked={draft.safety.warnLargeWordlists} onChange={(value) => updateDraft("safety", "warnLargeWordlists", value)} />
            <SettingToggle label="Defang IOCs in copied Markdown" description="Prefer safer report snippets for URLs, domains, and IP indicators." checked={draft.safety.defangMarkdownIocs} onChange={(value) => updateDraft("safety", "defangMarkdownIocs", value)} />
          </WorkbenchPanel>
        </div>
      )}

      {activeSection === "storage" && (
        <div className="space-y-4">
          <WorkbenchPanel className="space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <SectionTitle title="Local storage" subtitle={`Browser localStorage estimate: ${totalStorage}. Export files stay local until you share them.`} icon={HardDrive} />
              <Button icon={RefreshCw} onClick={refreshStorage}>Refresh</Button>
            </div>
            <div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-4">
              {rows.map((row) => <StorageCard key={row.id} item={row} onClear={clearKeys} />)}
            </div>
          </WorkbenchPanel>

          <div className="grid gap-4 xl:grid-cols-2">
            <WorkbenchPanel className="space-y-3">
              <SectionTitle title="Backup export" subtitle="Create reviewable JSON backups. Exports may contain analyst notes or artifacts." icon={Download} />
              <div className="flex flex-wrap gap-2">
                <Button icon={Download} onClick={() => exportPayload("settings")}>Export settings</Button>
                <Button icon={HardDrive} onClick={() => exportPayload("local-data")}>Export local data</Button>
                <Button icon={Database} onClick={() => exportPayload("investigation")}>Export case</Button>
              </div>
            </WorkbenchPanel>

            <WorkbenchPanel className="space-y-3">
              <SectionTitle title="Import backup" subtitle="Load a BeyondArch export, preview its keys, then apply it." icon={Import} />
              <textarea className="min-h-28 w-full rounded-xl border border-white/10 bg-black/50 p-3 font-mono text-sm text-zinc-100 outline-none placeholder:text-zinc-600" value={importText} onChange={(event) => { setImportText(event.target.value); setImportPreview(null) }} placeholder="Paste BeyondArch export JSON..." />
              <div className="flex flex-wrap gap-2">
                <Button icon={Upload} onClick={() => importFileRef.current?.click()}>Load JSON</Button>
                <input ref={importFileRef} type="file" accept="application/json,.json" className="hidden" onChange={importFromFile} />
                <Button icon={Import} onClick={previewImport}>Preview</Button>
                <Button icon={Upload} variant="primary" disabled={!importPreview} onClick={applyImport}>Apply import</Button>
              </div>
              {importPreview && (
                <div className="rounded-xl border border-cyan-500/25 bg-cyan-500/10 p-3 text-sm text-cyan-100">
                  Preview ready: {Object.keys(importPreview.data).length} item(s), mode: {importPreview.mode || "unknown"}.
                </div>
              )}
            </WorkbenchPanel>
          </div>

          <details className="rounded-xl border border-white/10 bg-black/40 p-3">
            <summary className="cursor-pointer text-sm font-bold text-zinc-100">Advanced: raw BeyondArch storage keys</summary>
            <div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">
              {rawRows.length ? rawRows.map((row) => (
                <div key={row.key} className="rounded-lg border border-white/10 bg-black/40 p-2">
                  <code className="text-xs text-cyan-100">{row.key}</code>
                  <p className="mt-1 text-xs text-zinc-400">{row.size}</p>
                </div>
              )) : <div className="flex flex-col items-center gap-2 py-4 text-center"><Database className="h-6 w-6 text-zinc-500" /><p className="text-sm text-zinc-400">No BeyondArch keys found.</p></div>}
            </div>
          </details>
        </div>
      )}

      {activeSection === "diagnostics" && (
        <div className="grid gap-4 xl:grid-cols-[0.95fr_1.05fr]">
          <WorkbenchPanel className="space-y-4">
            <SectionTitle title="Backend connection" subtitle="Checks only your configured local backend. No external services are contacted." icon={Database} />
            <label className="block rounded-xl border border-white/10 bg-black/40 p-3">
              <span className="text-sm font-bold text-zinc-100">Backend API URL</span>
              <input className="mt-2 w-full rounded-xl border border-white/10 bg-black/50 px-3 py-2 font-mono text-sm text-zinc-100 outline-none focus:border-cyan-400" value={draft.backend.apiUrl} onChange={(event) => updateDraft("backend", "apiUrl", event.target.value)} placeholder="http://127.0.0.1:8000" />
            </label>
          <div className="rounded-2xl border border-white/10 bg-black/40 p-4">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-xs uppercase tracking-[0.18em] text-zinc-400">Health status</p>
                  <p className="mt-1 flex items-center gap-2 text-lg font-black text-zinc-100">
                    {backendStatus.tone === "ready" ? <Wifi className="h-5 w-5 text-emerald-300" /> : backendStatus.tone === "danger" ? <WifiOff className="h-5 w-5 text-rose-300" /> : <Database className="h-5 w-5 text-cyan-300" />}
                    {backendStatus.label}
                  </p>
                </div>
                <StatusPill tone={backendStatus.tone}>{backendStatus.label}</StatusPill>
              </div>
              <p className="mt-3 text-sm leading-6 text-zinc-400">{backendStatus.detail}</p>
              <p className="mt-2 font-mono text-xs text-zinc-500">{backendBase}/health</p>
            </div>
            <div className="flex flex-wrap gap-2">
              <Button icon={MonitorCog} variant="primary" disabled={checkingBackend} onClick={checkBackend}>Check backend</Button>
              <Button icon={ExternalLink} onClick={openApiDocs}>Open API docs</Button>
              <Button icon={Clipboard} onClick={() => copyText(backendBase, setNotice, "Backend URL")}>Copy URL</Button>
              <Button icon={RefreshCw} onClick={refreshDiagnostics}>Refresh diagnostics</Button>
            </div>
          </WorkbenchPanel>

          <WorkbenchPanel className="space-y-4">
            <SectionTitle title="Installed workspace map" subtitle="Active pages shown in the current BeyondArch build." icon={Check} />
            <div className="grid gap-2 md:grid-cols-2">
              {ACTIVE_MODULES.map((module) => (
                <div key={module} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-black/40 p-3">
                  <span className="text-sm font-semibold text-zinc-100">{module}</span>
                  <StatusPill tone="ready">Available</StatusPill>
                </div>
              ))}
            </div>
          </WorkbenchPanel>
        </div>
      )}

      {activeSection === "reset" && (
        <div className="space-y-4">
          <WorkbenchPanel className="space-y-4">
            <SectionTitle title="Reset and clear data" subtitle="Destructive actions are separated here. Every action asks for confirmation." icon={AlertTriangle} />
            <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
            <div className="rounded-2xl border border-white/10 bg-black/40 p-4">
                <h3 className="font-black text-zinc-100">Reset settings</h3>
                <p className="mt-1 text-xs leading-5 text-zinc-400">Restore default preferences, theme, density, and backend URL.</p>
                <div className="mt-4"><Button icon={RotateCcw} onClick={resetSettings}>Reset defaults</Button></div>
              </div>
            <div className="rounded-2xl border border-white/10 bg-black/40 p-4">
                <h3 className="font-black text-zinc-100">Clear CyberChef</h3>
                <p className="mt-1 text-xs leading-5 text-zinc-400">Remove saved recipes, favorites, and previous recipe state.</p>
                <div className="mt-4"><Button icon={Trash2} onClick={clearCyberChef}>Clear CyberChef</Button></div>
              </div>
            <div className="rounded-2xl border border-white/10 bg-black/40 p-4">
                <h3 className="font-black text-zinc-100">Clear workspace</h3>
                <p className="mt-1 text-xs leading-5 text-zinc-400">Remove local case metadata, saved outputs, and pending handoffs.</p>
                <div className="mt-4"><Button icon={Trash2} onClick={clearWorkspace}>Clear workspace</Button></div>
              </div>
              <div className="rounded-2xl border border-rose-500/35 bg-rose-500/10 p-4">
                <h3 className="font-black text-rose-100">Clear everything</h3>
                <p className="mt-1 text-xs leading-5 text-rose-200/80">Remove every BeyondArch local key and restore defaults.</p>
                <div className="mt-4"><Button icon={Trash2} variant="danger" onClick={clearAll}>Clear all data</Button></div>
              </div>
            </div>
          </WorkbenchPanel>
        </div>
      )}
    </WorkbenchPage>
  )
}
