/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlRouteImport } from './routes/url'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SiemRouteImport } from './routes/siem'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReconRouteImport } from './routes/recon'
import { Route as PhishingRouteImport } from './routes/phishing'
import { Route as ParserRouteImport } from './routes/parser'
import { Route as OsintRouteImport } from './routes/osint'
import { Route as NmapRouteImport } from './routes/nmap'
import { Route as MitreRouteImport } from './routes/mitre'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HackingToolkitRouteImport } from './routes/hacking-toolkit'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as ChefRouteImport } from './routes/chef'
import { Route as CaseRouteImport } from './routes/case'
import { Route as AttachmentRouteImport } from './routes/attachment'
import { Route as IndexRouteImport } from './routes/index'

const UrlRoute = UrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SiemRoute = SiemRouteImport.update({
  id: '/siem',
  path: '/siem',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconRoute = ReconRouteImport.update({
  id: '/recon',
  path: '/recon',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingRoute = PhishingRouteImport.update({
  id: '/phishing',
  path: '/phishing',
  getParentRoute: () => rootRouteImport,
} as any)
const ParserRoute = ParserRouteImport.update({
  id: '/parser',
  path: '/parser',
  getParentRoute: () => rootRouteImport,
} as any)
const OsintRoute = OsintRouteImport.update({
  id: '/osint',
  path: '/osint',
  getParentRoute: () => rootRouteImport,
} as any)
const NmapRoute = NmapRouteImport.update({
  id: '/nmap',
  path: '/nmap',
  getParentRoute: () => rootRouteImport,
} as any)
const MitreRoute = MitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HackingToolkitRoute = HackingToolkitRouteImport.update({
  id: '/hacking-toolkit',
  path: '/hacking-toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRoute = ChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentRoute = AttachmentRouteImport.update({
  id: '/attachment',
  path: '/attachment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attachment': typeof AttachmentRoute
  '/case': typeof CaseRoute
  '/chef': typeof ChefRoute
  '/detection': typeof DetectionRoute
  '/guide': typeof GuideRoute
  '/hacking-toolkit': typeof HackingToolkitRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/nmap': typeof NmapRoute
  '/osint': typeof OsintRoute
  '/parser': typeof ParserRoute
  '/phishing': typeof PhishingRoute
  '/recon': typeof ReconRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/terminal': typeof TerminalRoute
  '/url': typeof UrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attachment': typeof AttachmentRoute
  '/case': typeof CaseRoute
  '/chef': typeof ChefRoute
  '/detection': typeof DetectionRoute
  '/guide': typeof GuideRoute
  '/hacking-toolkit': typeof HackingToolkitRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/nmap': typeof NmapRoute
  '/osint': typeof OsintRoute
  '/parser': typeof ParserRoute
  '/phishing': typeof PhishingRoute
  '/recon': typeof ReconRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/terminal': typeof TerminalRoute
  '/url': typeof UrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attachment': typeof AttachmentRoute
  '/case': typeof CaseRoute
  '/chef': typeof ChefRoute
  '/detection': typeof DetectionRoute
  '/guide': typeof GuideRoute
  '/hacking-toolkit': typeof HackingToolkitRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/nmap': typeof NmapRoute
  '/osint': typeof OsintRoute
  '/parser': typeof ParserRoute
  '/phishing': typeof PhishingRoute
  '/recon': typeof ReconRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/terminal': typeof TerminalRoute
  '/url': typeof UrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attachment'
    | '/case'
    | '/chef'
    | '/detection'
    | '/guide'
    | '/hacking-toolkit'
    | '/logs'
    | '/mitre'
    | '/nmap'
    | '/osint'
    | '/parser'
    | '/phishing'
    | '/recon'
    | '/settings'
    | '/siem'
    | '/terminal'
    | '/url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attachment'
    | '/case'
    | '/chef'
    | '/detection'
    | '/guide'
    | '/hacking-toolkit'
    | '/logs'
    | '/mitre'
    | '/nmap'
    | '/osint'
    | '/parser'
    | '/phishing'
    | '/recon'
    | '/settings'
    | '/siem'
    | '/terminal'
    | '/url'
  id:
    | '__root__'
    | '/'
    | '/attachment'
    | '/case'
    | '/chef'
    | '/detection'
    | '/guide'
    | '/hacking-toolkit'
    | '/logs'
    | '/mitre'
    | '/nmap'
    | '/osint'
    | '/parser'
    | '/phishing'
    | '/recon'
    | '/settings'
    | '/siem'
    | '/terminal'
    | '/url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttachmentRoute: typeof AttachmentRoute
  CaseRoute: typeof CaseRoute
  ChefRoute: typeof ChefRoute
  DetectionRoute: typeof DetectionRoute
  GuideRoute: typeof GuideRoute
  HackingToolkitRoute: typeof HackingToolkitRoute
  LogsRoute: typeof LogsRoute
  MitreRoute: typeof MitreRoute
  NmapRoute: typeof NmapRoute
  OsintRoute: typeof OsintRoute
  ParserRoute: typeof ParserRoute
  PhishingRoute: typeof PhishingRoute
  ReconRoute: typeof ReconRoute
  SettingsRoute: typeof SettingsRoute
  SiemRoute: typeof SiemRoute
  TerminalRoute: typeof TerminalRoute
  UrlRoute: typeof UrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url': {
      id: '/url'
      path: '/url'
      fullPath: '/url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siem': {
      id: '/siem'
      path: '/siem'
      fullPath: '/siem'
      preLoaderRoute: typeof SiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recon': {
      id: '/recon'
      path: '/recon'
      fullPath: '/recon'
      preLoaderRoute: typeof ReconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing': {
      id: '/phishing'
      path: '/phishing'
      fullPath: '/phishing'
      preLoaderRoute: typeof PhishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parser': {
      id: '/parser'
      path: '/parser'
      fullPath: '/parser'
      preLoaderRoute: typeof ParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osint': {
      id: '/osint'
      path: '/osint'
      fullPath: '/osint'
      preLoaderRoute: typeof OsintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nmap': {
      id: '/nmap'
      path: '/nmap'
      fullPath: '/nmap'
      preLoaderRoute: typeof NmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitre': {
      id: '/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof MitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacking-toolkit': {
      id: '/hacking-toolkit'
      path: '/hacking-toolkit'
      fullPath: '/hacking-toolkit'
      preLoaderRoute: typeof HackingToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef': {
      id: '/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof ChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachment': {
      id: '/attachment'
      path: '/attachment'
      fullPath: '/attachment'
      preLoaderRoute: typeof AttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttachmentRoute: AttachmentRoute,
  CaseRoute: CaseRoute,
  ChefRoute: ChefRoute,
  DetectionRoute: DetectionRoute,
  GuideRoute: GuideRoute,
  HackingToolkitRoute: HackingToolkitRoute,
  LogsRoute: LogsRoute,
  MitreRoute: MitreRoute,
  NmapRoute: NmapRoute,
  OsintRoute: OsintRoute,
  ParserRoute: ParserRoute,
  PhishingRoute: PhishingRoute,
  ReconRoute: ReconRoute,
  SettingsRoute: SettingsRoute,
  SiemRoute: SiemRoute,
  TerminalRoute: TerminalRoute,
  UrlRoute: UrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
