/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlRouteImport } from './routes/url'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ThreatActorsRouteImport } from './routes/threat-actors'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SnippetsRouteImport } from './routes/snippets'
import { Route as SigmaTesterRouteImport } from './routes/sigma-tester'
import { Route as SiemRouteImport } from './routes/siem'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegexPlaygroundRouteImport } from './routes/regex-playground'
import { Route as ReconRouteImport } from './routes/recon'
import { Route as PhishingRouteImport } from './routes/phishing'
import { Route as PcapRouteImport } from './routes/pcap'
import { Route as ParserRouteImport } from './routes/parser'
import { Route as OsintRouteImport } from './routes/osint'
import { Route as NmapRouteImport } from './routes/nmap'
import { Route as MitreRouteImport } from './routes/mitre'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as Ja3LookupRouteImport } from './routes/ja3-lookup'
import { Route as HashLookupRouteImport } from './routes/hash-lookup'
import { Route as HackingToolkitRouteImport } from './routes/hacking-toolkit'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as CveRouteImport } from './routes/cve'
import { Route as ChefRouteImport } from './routes/chef'
import { Route as CaseRouteImport } from './routes/case'
import { Route as AttachmentRouteImport } from './routes/attachment'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportCaseIdRouteImport } from './routes/report.$caseId'

const UrlRoute = UrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatActorsRoute = ThreatActorsRouteImport.update({
  id: '/threat-actors',
  path: '/threat-actors',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsRoute = SnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const SigmaTesterRoute = SigmaTesterRouteImport.update({
  id: '/sigma-tester',
  path: '/sigma-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const SiemRoute = SiemRouteImport.update({
  id: '/siem',
  path: '/siem',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegexPlaygroundRoute = RegexPlaygroundRouteImport.update({
  id: '/regex-playground',
  path: '/regex-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconRoute = ReconRouteImport.update({
  id: '/recon',
  path: '/recon',
  getParentRoute: () => rootRouteImport,
} as any)
const PhishingRoute = PhishingRouteImport.update({
  id: '/phishing',
  path: '/phishing',
  getParentRoute: () => rootRouteImport,
} as any)
const PcapRoute = PcapRouteImport.update({
  id: '/pcap',
  path: '/pcap',
  getParentRoute: () => rootRouteImport,
} as any)
const ParserRoute = ParserRouteImport.update({
  id: '/parser',
  path: '/parser',
  getParentRoute: () => rootRouteImport,
} as any)
const OsintRoute = OsintRouteImport.update({
  id: '/osint',
  path: '/osint',
  getParentRoute: () => rootRouteImport,
} as any)
const NmapRoute = NmapRouteImport.update({
  id: '/nmap',
  path: '/nmap',
  getParentRoute: () => rootRouteImport,
} as any)
const MitreRoute = MitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const Ja3LookupRoute = Ja3LookupRouteImport.update({
  id: '/ja3-lookup',
  path: '/ja3-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const HashLookupRoute = HashLookupRouteImport.update({
  id: '/hash-lookup',
  path: '/hash-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const HackingToolkitRoute = HackingToolkitRouteImport.update({
  id: '/hacking-toolkit',
  path: '/hacking-toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const CveRoute = CveRouteImport.update({
  id: '/cve',
  path: '/cve',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRoute = ChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentRoute = AttachmentRouteImport.update({
  id: '/attachment',
  path: '/attachment',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCaseIdRoute = ReportCaseIdRouteImport.update({
  id: '/report/$caseId',
  path: '/report/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/attachment': typeof AttachmentRoute
  '/case': typeof CaseRoute
  '/chef': typeof ChefRoute
  '/cve': typeof CveRoute
  '/detection': typeof DetectionRoute
  '/diff': typeof DiffRoute
  '/guide': typeof GuideRoute
  '/hacking-toolkit': typeof HackingToolkitRoute
  '/hash-lookup': typeof HashLookupRoute
  '/ja3-lookup': typeof Ja3LookupRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/nmap': typeof NmapRoute
  '/osint': typeof OsintRoute
  '/parser': typeof ParserRoute
  '/pcap': typeof PcapRoute
  '/phishing': typeof PhishingRoute
  '/recon': typeof ReconRoute
  '/regex-playground': typeof RegexPlaygroundRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/sigma-tester': typeof SigmaTesterRoute
  '/snippets': typeof SnippetsRoute
  '/terminal': typeof TerminalRoute
  '/threat-actors': typeof ThreatActorsRoute
  '/timeline': typeof TimelineRoute
  '/triage': typeof TriageRoute
  '/url': typeof UrlRoute
  '/report/$caseId': typeof ReportCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/attachment': typeof AttachmentRoute
  '/case': typeof CaseRoute
  '/chef': typeof ChefRoute
  '/cve': typeof CveRoute
  '/detection': typeof DetectionRoute
  '/diff': typeof DiffRoute
  '/guide': typeof GuideRoute
  '/hacking-toolkit': typeof HackingToolkitRoute
  '/hash-lookup': typeof HashLookupRoute
  '/ja3-lookup': typeof Ja3LookupRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/nmap': typeof NmapRoute
  '/osint': typeof OsintRoute
  '/parser': typeof ParserRoute
  '/pcap': typeof PcapRoute
  '/phishing': typeof PhishingRoute
  '/recon': typeof ReconRoute
  '/regex-playground': typeof RegexPlaygroundRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/sigma-tester': typeof SigmaTesterRoute
  '/snippets': typeof SnippetsRoute
  '/terminal': typeof TerminalRoute
  '/threat-actors': typeof ThreatActorsRoute
  '/timeline': typeof TimelineRoute
  '/triage': typeof TriageRoute
  '/url': typeof UrlRoute
  '/report/$caseId': typeof ReportCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/attachment': typeof AttachmentRoute
  '/case': typeof CaseRoute
  '/chef': typeof ChefRoute
  '/cve': typeof CveRoute
  '/detection': typeof DetectionRoute
  '/diff': typeof DiffRoute
  '/guide': typeof GuideRoute
  '/hacking-toolkit': typeof HackingToolkitRoute
  '/hash-lookup': typeof HashLookupRoute
  '/ja3-lookup': typeof Ja3LookupRoute
  '/logs': typeof LogsRoute
  '/mitre': typeof MitreRoute
  '/nmap': typeof NmapRoute
  '/osint': typeof OsintRoute
  '/parser': typeof ParserRoute
  '/pcap': typeof PcapRoute
  '/phishing': typeof PhishingRoute
  '/recon': typeof ReconRoute
  '/regex-playground': typeof RegexPlaygroundRoute
  '/settings': typeof SettingsRoute
  '/siem': typeof SiemRoute
  '/sigma-tester': typeof SigmaTesterRoute
  '/snippets': typeof SnippetsRoute
  '/terminal': typeof TerminalRoute
  '/threat-actors': typeof ThreatActorsRoute
  '/timeline': typeof TimelineRoute
  '/triage': typeof TriageRoute
  '/url': typeof UrlRoute
  '/report/$caseId': typeof ReportCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/attachment'
    | '/case'
    | '/chef'
    | '/cve'
    | '/detection'
    | '/diff'
    | '/guide'
    | '/hacking-toolkit'
    | '/hash-lookup'
    | '/ja3-lookup'
    | '/logs'
    | '/mitre'
    | '/nmap'
    | '/osint'
    | '/parser'
    | '/pcap'
    | '/phishing'
    | '/recon'
    | '/regex-playground'
    | '/settings'
    | '/siem'
    | '/sigma-tester'
    | '/snippets'
    | '/terminal'
    | '/threat-actors'
    | '/timeline'
    | '/triage'
    | '/url'
    | '/report/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/attachment'
    | '/case'
    | '/chef'
    | '/cve'
    | '/detection'
    | '/diff'
    | '/guide'
    | '/hacking-toolkit'
    | '/hash-lookup'
    | '/ja3-lookup'
    | '/logs'
    | '/mitre'
    | '/nmap'
    | '/osint'
    | '/parser'
    | '/pcap'
    | '/phishing'
    | '/recon'
    | '/regex-playground'
    | '/settings'
    | '/siem'
    | '/sigma-tester'
    | '/snippets'
    | '/terminal'
    | '/threat-actors'
    | '/timeline'
    | '/triage'
    | '/url'
    | '/report/$caseId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/attachment'
    | '/case'
    | '/chef'
    | '/cve'
    | '/detection'
    | '/diff'
    | '/guide'
    | '/hacking-toolkit'
    | '/hash-lookup'
    | '/ja3-lookup'
    | '/logs'
    | '/mitre'
    | '/nmap'
    | '/osint'
    | '/parser'
    | '/pcap'
    | '/phishing'
    | '/recon'
    | '/regex-playground'
    | '/settings'
    | '/siem'
    | '/sigma-tester'
    | '/snippets'
    | '/terminal'
    | '/threat-actors'
    | '/timeline'
    | '/triage'
    | '/url'
    | '/report/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AttachmentRoute: typeof AttachmentRoute
  CaseRoute: typeof CaseRoute
  ChefRoute: typeof ChefRoute
  CveRoute: typeof CveRoute
  DetectionRoute: typeof DetectionRoute
  DiffRoute: typeof DiffRoute
  GuideRoute: typeof GuideRoute
  HackingToolkitRoute: typeof HackingToolkitRoute
  HashLookupRoute: typeof HashLookupRoute
  Ja3LookupRoute: typeof Ja3LookupRoute
  LogsRoute: typeof LogsRoute
  MitreRoute: typeof MitreRoute
  NmapRoute: typeof NmapRoute
  OsintRoute: typeof OsintRoute
  ParserRoute: typeof ParserRoute
  PcapRoute: typeof PcapRoute
  PhishingRoute: typeof PhishingRoute
  ReconRoute: typeof ReconRoute
  RegexPlaygroundRoute: typeof RegexPlaygroundRoute
  SettingsRoute: typeof SettingsRoute
  SiemRoute: typeof SiemRoute
  SigmaTesterRoute: typeof SigmaTesterRoute
  SnippetsRoute: typeof SnippetsRoute
  TerminalRoute: typeof TerminalRoute
  ThreatActorsRoute: typeof ThreatActorsRoute
  TimelineRoute: typeof TimelineRoute
  TriageRoute: typeof TriageRoute
  UrlRoute: typeof UrlRoute
  ReportCaseIdRoute: typeof ReportCaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url': {
      id: '/url'
      path: '/url'
      fullPath: '/url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-actors': {
      id: '/threat-actors'
      path: '/threat-actors'
      fullPath: '/threat-actors'
      preLoaderRoute: typeof ThreatActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets': {
      id: '/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof SnippetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigma-tester': {
      id: '/sigma-tester'
      path: '/sigma-tester'
      fullPath: '/sigma-tester'
      preLoaderRoute: typeof SigmaTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siem': {
      id: '/siem'
      path: '/siem'
      fullPath: '/siem'
      preLoaderRoute: typeof SiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regex-playground': {
      id: '/regex-playground'
      path: '/regex-playground'
      fullPath: '/regex-playground'
      preLoaderRoute: typeof RegexPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recon': {
      id: '/recon'
      path: '/recon'
      fullPath: '/recon'
      preLoaderRoute: typeof ReconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phishing': {
      id: '/phishing'
      path: '/phishing'
      fullPath: '/phishing'
      preLoaderRoute: typeof PhishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcap': {
      id: '/pcap'
      path: '/pcap'
      fullPath: '/pcap'
      preLoaderRoute: typeof PcapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parser': {
      id: '/parser'
      path: '/parser'
      fullPath: '/parser'
      preLoaderRoute: typeof ParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osint': {
      id: '/osint'
      path: '/osint'
      fullPath: '/osint'
      preLoaderRoute: typeof OsintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nmap': {
      id: '/nmap'
      path: '/nmap'
      fullPath: '/nmap'
      preLoaderRoute: typeof NmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitre': {
      id: '/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof MitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja3-lookup': {
      id: '/ja3-lookup'
      path: '/ja3-lookup'
      fullPath: '/ja3-lookup'
      preLoaderRoute: typeof Ja3LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash-lookup': {
      id: '/hash-lookup'
      path: '/hash-lookup'
      fullPath: '/hash-lookup'
      preLoaderRoute: typeof HashLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacking-toolkit': {
      id: '/hacking-toolkit'
      path: '/hacking-toolkit'
      fullPath: '/hacking-toolkit'
      preLoaderRoute: typeof HackingToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cve': {
      id: '/cve'
      path: '/cve'
      fullPath: '/cve'
      preLoaderRoute: typeof CveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef': {
      id: '/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof ChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachment': {
      id: '/attachment'
      path: '/attachment'
      fullPath: '/attachment'
      preLoaderRoute: typeof AttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$caseId': {
      id: '/report/$caseId'
      path: '/report/$caseId'
      fullPath: '/report/$caseId'
      preLoaderRoute: typeof ReportCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AttachmentRoute: AttachmentRoute,
  CaseRoute: CaseRoute,
  ChefRoute: ChefRoute,
  CveRoute: CveRoute,
  DetectionRoute: DetectionRoute,
  DiffRoute: DiffRoute,
  GuideRoute: GuideRoute,
  HackingToolkitRoute: HackingToolkitRoute,
  HashLookupRoute: HashLookupRoute,
  Ja3LookupRoute: Ja3LookupRoute,
  LogsRoute: LogsRoute,
  MitreRoute: MitreRoute,
  NmapRoute: NmapRoute,
  OsintRoute: OsintRoute,
  ParserRoute: ParserRoute,
  PcapRoute: PcapRoute,
  PhishingRoute: PhishingRoute,
  ReconRoute: ReconRoute,
  RegexPlaygroundRoute: RegexPlaygroundRoute,
  SettingsRoute: SettingsRoute,
  SiemRoute: SiemRoute,
  SigmaTesterRoute: SigmaTesterRoute,
  SnippetsRoute: SnippetsRoute,
  TerminalRoute: TerminalRoute,
  ThreatActorsRoute: ThreatActorsRoute,
  TimelineRoute: TimelineRoute,
  TriageRoute: TriageRoute,
  UrlRoute: UrlRoute,
  ReportCaseIdRoute: ReportCaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
