export const KNOWLEDGE_BASE = [
  {
    id: "phishing-triage",
    category: "Phishing",
    title: "Phishing email triage checklist",
    summary: "Review sender alignment, authentication, URLs, attachments, language, and user impact before deciding.",
    tags: ["email", "triage", "spf", "dkim", "dmarc"],
    steps: [
      "Check From, Reply-To, Return-Path, and Message-ID domains for mismatch.",
      "Review SPF, DKIM, and DMARC results, but do not treat pass/fail as a complete verdict.",
      "Extract URLs and compare visible text, href destination, redirects, and final domain.",
      "Look for credential-theft language, urgency, invoice/payment lures, and attachment pressure.",
      "Record evidence and limitations in the case timeline/report.",
    ],
    pivots: ["Safe URL Analyzer", "Recon & Exposure", "Case Timeline", "Report Builder"],
  },
  {
    id: "url-analysis",
    category: "URLs & Domains",
    title: "Safe URL analysis workflow",
    summary: "Analyze structure first, then optional guarded metadata only when scope allows.",
    tags: ["url", "redirect", "defang", "domain"],
    steps: [
      "Refang only inside the tool and keep report output defanged.",
      "Check scheme, host, root domain, path, query parameters, and encoded blobs.",
      "Review redirect count, status chain, content type, headers, and TLS context if metadata mode is allowed.",
      "Pivot domains/IPs into DNS, proxy, firewall, and endpoint logs.",
      "Use third-party reputation only when privacy/scope permits.",
    ],
    pivots: ["Safe URL Analyzer", "Recon & Exposure", "Logs & Alerts"],
  },
  {
    id: "auth-logs",
    category: "Logs",
    title: "Authentication log investigation",
    summary: "Failed and successful logons become meaningful when correlated by source, account, host, and time.",
    tags: ["auth", "4624", "4625", "sshd", "vpn"],
    steps: [
      "Group failed logins by user, source IP, and time window.",
      "Look for success after failures, privileged accounts, impossible travel, or unusual hosts.",
      "Check MFA, VPN, EDR, and endpoint process activity around the same time.",
      "Document whether the pattern is spray, brute force, user error, or expected admin behavior.",
    ],
    pivots: ["Logs & Alerts", "SIEM Workspace", "Timeline"],
  },
  {
    id: "web-logs",
    category: "Logs",
    title: "Web access log review",
    summary: "Focus on method, path, status, user agent, source, referrer, and repeated paths.",
    tags: ["web", "http", "proxy", "waf"],
    steps: [
      "Identify scanner strings, traversal attempts, SQLi/XSS patterns, and admin-path access.",
      "Compare status codes with volume and response sizes.",
      "Pivot source IP and user agent across nearby requests.",
      "Confirm whether the request reached the app or was blocked upstream.",
    ],
    pivots: ["Query Builder", "SIEM Workspace", "Recon"],
  },
  {
    id: "windows-events",
    category: "Windows",
    title: "Windows Event IDs worth knowing",
    summary: "Common IDs: 4624 success, 4625 failure, 4672 privileged logon, 4688 process creation, 7045 service install, 1102 audit log cleared.",
    tags: ["windows", "sysmon", "eventid"],
    steps: [
      "Treat Event IDs as telemetry, not conclusions.",
      "For 4688/Sysmon 1, review parent process, command line, user, path, and hashes.",
      "For 1102, validate admin maintenance versus anti-forensics.",
      "For 7045, review service path, user, host role, and nearby network activity.",
    ],
    pivots: ["SOC Guide", "Detection & MITRE", "Report"],
  },
  {
    id: "detection-rules",
    category: "Detection",
    title: "Detection rule quality checklist",
    summary: "A useful rule describes behavior, maps evidence, avoids broad false positives, and includes test data.",
    tags: ["sigma", "suricata", "snort", "mitre"],
    steps: [
      "State the behavior and attacker technique you are trying to detect.",
      "Use specific fields and conditions instead of one broad keyword where possible.",
      "Document false positives and required log source.",
      "Test against sample benign and suspicious events before adding to a report.",
      "Map to MITRE only when there is evidence for the technique.",
    ],
    pivots: ["Detection Workspace", "Detection & MITRE", "Logs & Alerts"],
  },
  {
    id: "local-first",
    category: "Privacy",
    title: "Local-first investigation handling",
    summary: "Keep sensitive artifacts local unless the case scope permits external enrichment.",
    tags: ["privacy", "storage", "case"],
    steps: [
      "Use session-only storage by default for sensitive analysis.",
      "Clear local investigation data before switching cases or using shared machines.",
      "Defang URLs in notes and reports.",
      "Export JSON/Markdown only when the output is safe to store outside the browser.",
    ],
    pivots: ["Settings", "Case Timeline", "Report Export"],
  },
  {
    id: "dns-analysis",
    category: "Logs",
    title: "DNS log analysis for C2 detection",
    summary: "DNS logs reveal beaconing patterns, DGA domains, unusual TLDs, and high query volumes that indicate compromise.",
    tags: ["dns", "c2", "beacon", "nxdomain", "dga"],
    steps: [
      "Extract unique query domains and sort by frequency to find beacon-like patterns.",
      "Check for NXDOMAIN spikes which may indicate DGA domain generation.",
      "Review TLD distribution — .tk, .ml, .ga, .top, .xyz are common in C2 infrastructure.",
      "Check subdomain depth and label length — DGA domains often have long random strings.",
      "Correlate DNS queries with process execution logs and network connections.",
    ],
    pivots: ["Logs & Alerts", "SIEM Workspace", "Detection & MITRE"],
  },
  {
    id: "lateral-movement",
    category: "Windows",
    title: "Lateral movement detection patterns",
    summary: "Track service creation, RDP inbound, WinRM, PsExec, and SMB access from non-admin sources.",
    tags: ["lateral", "rdp", "psexec", "winrm", "smb", "7045", "4624"],
    steps: [
      "Correlate EventCode 7045 service install with 4624 logon events on the same host.",
      "Logon Type 3 (network), 10 (remote), and 9 (RunAs) are the most relevant for lateral movement.",
      "Check for PsExec service names (PSEXESVC.exe) and SMB admin share access (ADMIN$, IPC$).",
      "Review source IP geography — lateral movement from non-admin jump hosts is suspicious.",
      "Pivot to network connections (Sysmon 3) from the target host back to the source.",
    ],
    pivots: ["SOC Guide", "Detection & MITRE", "Logs & Alerts"],
  },
  {
    id: "service-persistence",
    category: "Windows",
    title: "Service and scheduled task persistence",
    summary: "New services, scheduled tasks, registry Run keys, and startup folders are common persistence mechanisms.",
    tags: ["persistence", "service", "scheduledtask", "runkey", "7045", "4698"],
    steps: [
      "Review EventCode 7045 (service) and 4698 (scheduled task) for unexpected creations.",
      "Check service binary path, arguments, and account context for anomalies.",
      "Correlate creation time with known installs, patch cycles, or change windows.",
      "Review Sysmon 13 (registry) for modification of Run/RunOnce keys.",
      "Investigate the creating process and prior logon events for unauthorized access.",
    ],
    pivots: ["SOC Guide", "Detection & MITRE", "SIEM Workspace"],
  },
  {
    id: "cloud-iam",
    category: "Cloud",
    title: "Cloud IAM and access review",
    summary: "Monitor console logins, user/role creation, policy changes, and privilege escalation paths.",
    tags: ["cloud", "iam", "aws", "azure", "cloudtrail"],
    steps: [
      "Review ConsoleLogin events for unusual regions, MFA status, and user agent.",
      "Check CreateUser, CreateLoginProfile, and AttachUserPolicy for unauthorized IAM changes.",
      "Detect PassRole or SetDefaultPolicyVersion as privilege escalation preparation.",
      "Monitor DeleteLogGroup and StopTrail as anti-forensics indicators.",
      "Correlate cloud IAM events with on-premise logs for hybrid environment coverage.",
    ],
    pivots: ["Logs & Alerts", "SIEM Workspace", "Detection & MITRE"],
  },
  {
    id: "ransomware-indicators",
    category: "Detection",
    title: "Ransomware early warning indicators",
    summary: "Detect early ransomware stages: shadow copy deletion, encryption flags, mass file renames, and ransom notes.",
    tags: ["ransomware", "shadowcopy", "vssadmin", "encryption"],
    steps: [
      "Alert on vssadmin delete shadows, wmic shadowcopy delete, or bcdedit boot recovery disable.",
      "Detect mass file rename operations (.locked, .encrypted, .crypt) within a short window.",
      "Correlate process creation 4688/Sysmon 1 with file creation events 4663/11.",
      "Look for ransom note file creation (README.txt, HOW_TO_DECRYPT, etc.) in shared directories.",
      "Isolate affected hosts and preserve raw disk evidence before any recovery steps.",
    ],
    pivots: ["Detection & MITRE", "Logs & Alerts", "SIEM Workspace"],
  },
  {
    id: "defender-evasion",
    category: "Detection",
    title: "Defender and AMSI evasion detection",
    summary: "Detect attempts to bypass Windows Defender, AMSI, and other endpoint security controls.",
    tags: ["defender", "amsi", "evasion", "tamper", "mppreference"],
    steps: [
      "Monitor Add-MpPreference -ExclusionPath and Set-MpPreference -DisableRealtimeMonitoring.",
      "Detect AMSI bypass techniques (AmsiScanBuffer patching, Wldp query suppression).",
      "Alert on registry modification of Defender service keys (DisableAntiSpyware).",
      "Look for PowerShell -EncodedCommand combined with execution policy bypass.",
      "ETW bypass (Event Tracing for Windows) via registry or .NET configuration changes.",
    ],
    pivots: ["SOC Guide", "Detection & MITRE", "Logs & Alerts"],
  },
]

export function searchKnowledgeBase(query = "", category = "all") {
  const needle = String(query || "").trim().toLowerCase()
  return KNOWLEDGE_BASE.filter((entry) => {
    const matchesCategory = category === "all" || entry.category === category
    const haystack = `${entry.category} ${entry.title} ${entry.summary} ${entry.tags.join(" ")} ${entry.steps.join(" ")}`.toLowerCase()
    return matchesCategory && (!needle || haystack.includes(needle))
  })
}

export const KNOWLEDGE_CATEGORIES = ["all", ...Array.from(new Set(KNOWLEDGE_BASE.map((entry) => entry.category)))]
